// MamaHQ — The First 90 Days daily reads. Generated from
// public/MamaHQ_First_90_Days_Editorial_Collection.docx (audited editorial
// collection). One contextual read per day, surfaced on Today by the baby's day
// number. Category is an editorial tag ("For Mom", "Mental Load", ...). Content is
// human-written and safety-reviewed; do not hand-edit — regenerate from the source.
//
// The day number is sequencing metadata (the collection can show or omit it).
// Read time is estimated from word count at ~200 wpm.

export interface DailyRead {
  day: number
  category: string
  title: string
  /** Body paragraphs, in order. */
  body: string[]
  /** The closing "For today" prompt, when the piece has one. */
  prompt?: string
}

// The full collection, in day order.
export const ALL_READS: DailyRead[] = [
  {
    day: 1,
    category: 'For Mom',
    title: 'You Don\'t Need to Know What You\'re Doing Yet',
    body: [
      'You and your baby just met. You are not supposed to understand every sound, every preference, or every decision on the first day.',
      'Early motherhood can create the strange expectation that love should arrive with expertise. It doesn\'t. Expertise comes later, through repetition: holding, watching, asking, trying, adjusting, and slowly learning this particular little person.',
      'Today does not need a routine. It does not need a perfect plan. It does not need to prove anything about the kind of mother you will be.',
      'Be curious. Ask questions. Accept useful help. Let today be new.',
    ],
    prompt: 'don\'t try to master motherhood. Take care of what is in front of you. Tomorrow, you will know a little more.',
  },
  {
    day: 2,
    category: 'For Mom',
    title: 'Make Today Smaller',
    body: [
      'Your brain may already be trying to solve next week.',
      'Sleep. Feeding. Visitors. Appointments. Work. The house. Whether you\'re doing any of this correctly.',
      'You don\'t need to solve all of that today.',
      'When life changes this quickly, shrinking the horizon can be useful. What actually needs attention in the next hour? What can safely wait? What can someone else handle?',
      'A small day is not an unambitious day. Sometimes it is exactly the right size.',
    ],
    prompt: 'when your mind races ahead, ask, “What actually needs me right now?” Do that. Let the rest wait.',
  },
  {
    day: 3,
    category: 'Mental Load',
    title: 'Let People Help Without Managing Them',
    body: [
      'Help stops feeling like help when you have to plan it, explain it, supervise it, and check it afterward.',
      'If someone trustworthy offers to help, try giving them a complete outcome rather than a tiny task. Not “Can you help with dinner?” but “Can you take care of dinner tonight?”',
      'The difference matters. One still leaves you managing the work. The other removes something from your head.',
      'Not everything will be done exactly the way you would do it. If the result is safe and good enough, that may be a worthwhile trade.',
    ],
    prompt: 'choose one thing another capable person can own from beginning to end. Then let them own it.',
  },
  {
    day: 4,
    category: 'Boundaries',
    title: 'Your Job Isn\'t to Entertain Visitors',
    body: [
      'Your home is not a hospitality venue right now.',
      'You do not need to clean before people arrive, make coffee for everyone, apologize for the laundry, or hand over the baby because someone came to visit.',
      'Useful visitors reduce the burden. They bring food, wash a few dishes, take out garbage, walk the dog, entertain an older child, pick something up, or simply sit with you without expecting a performance.',
      'You are also allowed to say no.',
      'A complete sentence can be: “Today isn\'t a good day for visitors. We\'ll let you know when we\'re ready.”',
      'Protecting your energy is not rude. It is part of taking care of a household that has just changed dramatically.',
    ],
    prompt: undefined,
  },
  {
    day: 5,
    category: 'For Mom',
    title: 'You Can Love This and Still Find It Hard',
    body: [
      'Newborn life can be beautiful and exhausting, intimate and lonely, joyful and confusing — sometimes in the same hour.',
      'Loving your baby does not require enjoying every part of this experience. Missing freedom does not cancel gratitude. Wanting a break does not cancel love.',
      'Instead of asking, “Why aren\'t I enjoying this more?” try asking, “What would make today a little easier?”',
      'If sadness, anxiety, hopelessness, frightening thoughts, or other difficult feelings feel intense, persistent, or hard to manage, tell a health-care professional. Postpartum mental-health conditions are treatable, and asking for help matters.',
      'You do not have to turn every hard feeling into a lesson. Sometimes it is enough to name it and get support.',
    ],
    prompt: undefined,
  },
  {
    day: 6,
    category: 'Quick Read',
    title: 'The House Can Wait',
    body: [
      'A baby arrived. Your household is adapting. This is not the moment to judge yourself by the countertops.',
      'Try sorting household work into three categories: must happen, would be nice, can wait.',
      'You may be surprised how much belongs in the third category.',
      'The home is supposed to support the people living in it. The people do not exist to keep the home permanently ready for inspection.',
    ],
    prompt: 'do what genuinely matters. Let something visible remain unfinished without turning it into evidence that you are failing.',
  },
  {
    day: 7,
    category: 'Milestone',
    title: 'One Week: Notice What You\'ve Learned',
    body: [
      'One week is not enough time to have everything figured out. It is enough time to have learned more than you may realize.',
      'You have begun noticing sounds, movements, preferences, patterns, and your own limits. Some things that felt intimidating a few days ago may already feel slightly more familiar.',
      'Take one picture of ordinary life today if you want to: the bassinet, tiny socks, the chair you keep sitting in, reheated coffee, a burp cloth over someone\'s shoulder.',
      'Not every memory needs to be beautiful. Ordinary details are often the ones that disappear first.',
      'There is no grade for this week. Just notice that you lived it.',
    ],
    prompt: undefined,
  },
  {
    day: 8,
    category: 'For Mom',
    title: 'Rest Doesn\'t Have to Mean Sleep',
    body: [
      '“Sleep when the baby sleeps” sounds simple until the baby sleeps while you\'re hungry, showering, answering a necessary message, caring for another child, or lying awake with a brain that refuses to switch off.',
      'Sleep matters, but don\'t turn sleep into another task you can fail.',
      'Rest can also mean lying down, closing your eyes, letting someone else handle the next thing, or deciding that a quiet window does not need to become a productivity window.',
      'Instead of “I must sleep now,” try: “I don\'t need to accomplish anything right now.”',
      'Sometimes removing the expectation is what finally lets your body settle.',
    ],
    prompt: undefined,
  },
  {
    day: 9,
    category: 'Share With Your Partner',
    title: 'Your Partner Shouldn\'t Be \'Helping\'',
    body: [
      'When another parent or partner says, “Just tell me what you need,” the intention may be generous. But one person is still responsible for noticing, remembering, assigning, and following up.',
      'Where possible, aim for shared ownership.',
      '“Tell me when the baby needs changing” is assistance.',
      '“I\'ve got the next change” is ownership.',
      '“Tell me what we need from the store” is assistance.',
      '“I\'ll handle groceries this week” is ownership.',
      'Families will divide responsibilities differently. The goal is not a perfect 50/50 score. The goal is to prevent one person from becoming the permanent manager of everyone else.',
      'Pick one recurring responsibility another adult can own completely.',
    ],
    prompt: undefined,
  },
  {
    day: 10,
    category: 'For Mom',
    title: 'You Already Know More Than You Think',
    body: [
      'Think about something that felt intimidating at the beginning.',
      'Maybe it was holding your baby, changing them, preparing a feed, settling them, or simply being alone with the responsibility.',
      'Now notice what has become a little more ordinary.',
      'Confidence rarely arrives as a dramatic feeling of “I\'ve got this.” More often, something simply requires less thought than it did before.',
      'When you hear yourself say, “I have no idea what I\'m doing,” add one word:',
      'Yet.',
      'You are learning through repetition. That is how almost every difficult skill becomes familiar.',
    ],
    prompt: undefined,
  },
  {
    day: 11,
    category: 'For Mom',
    title: 'A Hard Morning Doesn\'t Get the Whole Day',
    body: [
      'Maybe the night was terrible. Maybe everyone cried. Maybe you\'ve already lost patience and it isn\'t even lunchtime.',
      'A rough beginning does not own the rest of the day.',
      'You can restart at 10:30, 2:17, or 6:45. Open the curtains. Eat something. Change rooms. Wash your face. Ask for backup. Step outside if that feels good and is practical.',
      'None of those things erase what happened. They simply draw a line that says: we begin again here.',
    ],
    prompt: 'don\'t rescue the entire day. Ask what would make the next hour better.',
  },
  {
    day: 12,
    category: 'For Mom',
    title: 'You Can Miss Your Old Life',
    body: [
      'You can love your baby and miss the life you had before them.',
      'You can miss spontaneous plans, uninterrupted sleep, your old relationship rhythm, your body, your work, your freedom, or simply being responsible mostly for yourself.',
      'Those feelings do not require a guilty verdict.',
      'Two things can be true: I love this life, and this transition has cost me something.',
      'Try asking what tiny piece of your old life you miss most. Is there a small version you could bring back — one song, one breakfast, ten minutes with a book, a call with someone who knew you before “Mom”?',
      'You are still in there.',
    ],
    prompt: undefined,
  },
  {
    day: 13,
    category: 'Worth Knowing',
    title: 'Don\'t Let a 2 A.M. Search Spiral Decide the Night',
    body: [
      'When you\'re exhausted and worried, the internet can turn one question into seventeen frightening possibilities.',
      'Information is useful. Context matters more.',
      'For health and safety questions, favour reliable health authorities and your baby\'s health-care team over anonymous forums and viral advice. If something genuinely concerns you, you do not need to become an amateur diagnostician before asking for help.',
      'When you feel the search spiral starting, stop and write the actual question: What am I trying to find out?',
      'If it can wait, save it for a trusted professional. If you think your baby needs urgent medical attention, seek appropriate care rather than continuing to search.',
      'Information should make you more capable, not more frightened.',
    ],
    prompt: undefined,
  },
  {
    day: 14,
    category: 'Milestone',
    title: 'Two Weeks: You\'re Still at the Beginning',
    body: [
      'Two weeks can sound like a deadline: surely there should be a routine by now, surely something should feel normal.',
      'There is no universal two-week finish line.',
      'Bodies recover differently. Babies differ. Support differs. Feeding experiences differ. Sleep differs. Families differ.',
      'Instead of measuring yourself against where you imagined you would be, ask a gentler and more useful question: what has become slightly easier?',
      'Progress in early parenthood is often quiet. It looks like one less thing feeling completely unfamiliar.',
    ],
    prompt: undefined,
  },
  {
    day: 15,
    category: 'For Mom',
    title: 'There Is No Medal for Doing It Alone',
    body: [
      'Mothers are often praised for carrying enormous amounts: she does everything, she never complains, she holds the family together.',
      'That can sound like admiration while describing an unsustainable system.',
      'Being capable of carrying everything does not mean you should. You do not prove love by becoming exhausted.',
      'Before you reach the point of desperation, look for something that does not specifically require you. Dinner. Laundry. A pickup. A phone call. A recurring household task.',
      'Then ask: why am I still the person doing this?',
      'The goal is not to become stronger at carrying an impossible load. It is to make the load lighter.',
    ],
    prompt: undefined,
  },
  {
    day: 16,
    category: 'For Mom',
    title: 'Your Basic Needs Are Family Needs',
    body: [
      'Food. Water. Medication you normally take. A shower. A bathroom break without rushing. Rest. A few minutes of quiet.',
      'These are not rewards for completing the household list.',
      'The list may never be complete.',
      'Before asking, “What needs to get done?” ask, “What do I need?”',
      'Sometimes the most useful thing you can do for your family is eat lunch, refill your water, take prescribed medication as directed, or sit down.',
      'You are not an accessory to the household. You are one of the people the household is supposed to care for.',
    ],
    prompt: undefined,
  },
  {
    day: 17,
    category: 'Worth Knowing',
    title: 'The Routine Isn\'t Broken. Today Is Just Different.',
    body: [
      'Yesterday worked. Today doesn\'t.',
      'It is tempting to treat every change as evidence that you did something wrong.',
      'But babies change, and family rhythms change with them. Something useful yesterday may be less useful today. A routine can support your family without becoming a test your family has to pass.',
      'Think rhythm, not perfection.',
      'Instead of asking, “How do I get yesterday back?” ask, “What does today seem to need?”',
      'Adaptability is a form of confidence too.',
    ],
    prompt: undefined,
  },
  {
    day: 18,
    category: 'Mental Load',
    title: 'Invisible Work Is Still Work',
    body: [
      'Caregiving can consume an entire day while leaving almost no visible evidence.',
      'You fed, changed, comforted, watched, cleaned, prepared, remembered, worried, learned, and repeated.',
      'Then someone asks what you did today and “nothing” comes out.',
      'The problem is not that you did nothing. Much of caregiving disappears as soon as it is performed. The baby needs feeding again. The dishes return. The laundry returns.',
      'Repeated work is still work.',
      'Tonight, instead of asking what you got done, ask who you cared for. Include yourself if you can.',
    ],
    prompt: undefined,
  },
  {
    day: 19,
    category: 'Share With Your Partner',
    title: 'Don\'t Make Mom the Family Project Manager',
    body: [
      'Doing a task is only one layer of responsibility.',
      'Someone also has to notice it, remember it, plan it, and make sure it happens.',
      'That is why “Just tell me what to do” can still leave one person carrying most of the mental load.',
      'Choose three recurring responsibilities and decide who owns each one. Ownership means: notice it, remember it, plan it, do it, follow through.',
      'The point is not rigid equality. The point is visibility.',
      'If one person is always the household\'s memory, dispatcher, and quality-control department, the workload is not truly shared.',
    ],
    prompt: undefined,
  },
  {
    day: 20,
    category: 'For Mom',
    title: 'Notice What Your Hands Already Know',
    body: [
      'At the beginning, ordinary tasks required thought.',
      'Now your hands may reach for things automatically. You know where supplies live. You recognize little movements. You have tiny systems you never formally designed.',
      'That is progress, even if it doesn\'t feel impressive.',
      'Confidence often arrives as reduced friction. Something that once took your full attention now happens while you\'re thinking about something else.',
      'You learned that by living it.',
    ],
    prompt: 'notice one thing your hands seem to know now.',
  },
  {
    day: 21,
    category: 'For Mom',
    title: 'You\'re Building a Relationship, Not Following a Manual',
    body: [
      'Advice can be useful, contradictory, outdated, brilliant, irritating, or all of those things in one afternoon.',
      'Underneath it is a simple truth: you are getting to know a person.',
      'Your baby is not an average, a schedule, or somebody else\'s experience. You are collecting hundreds of tiny observations about this particular child.',
      'Reliable health and safety guidance matters. Professional advice matters. So does the knowledge you build by paying attention.',
      'Treat advice as input, not an automatic instruction. Keep what is useful. Ask questions. Check important claims. Let the rest go.',
    ],
    prompt: undefined,
  },
  {
    day: 22,
    category: 'Practical',
    title: 'Make Leaving the House Easier Than Remembering Everything',
    body: [
      'Leaving home can suddenly feel like an expedition.',
      'The solution is not becoming better at remembering twelve things while sleep deprived. Build a repeatable system.',
      'Keep commonly used items together. Restock the bag when you return. Save a leaving-the-house checklist. Put recurring items where another caregiver can find them.',
      'And if you forget something occasionally, you are human.',
      'The goal is not perfect preparedness. It is reducing the amount of thinking required to get through the front door.',
    ],
    prompt: undefined,
  },
  {
    day: 23,
    category: 'For Mom',
    title: 'Stop Asking, \'Am I Doing Enough?\'',
    body: [
      'Motherhood can move the finish line all day.',
      'Settle the baby, notice the laundry. Finish the laundry, remember the dishes. Answer messages, wonder whether you should be doing something enriching.',
      'If “enough” means everything that could possibly be done, you will never reach it.',
      'Enough can mean the important things happened. The baby was cared for. You ate. Everyone is safe. The urgent thing got handled.',
      'Before adding something to today\'s list, ask whether it actually needs to happen today.',
      'Enough is not everything. That is the point.',
    ],
    prompt: undefined,
  },
  {
    day: 24,
    category: 'For Mom',
    title: 'Other Moms Are Not Your Report Card',
    body: [
      'Comparison becomes brutal when you compare the inside of your life with the outside of someone else\'s.',
      'You know every hard part of your day. You do not know who helped her, what happened before the photo, what recovery has been like, what her baby needs, or what she never posts.',
      'Different families have different support, money, schedules, bodies, babies, and circumstances.',
      'If someone\'s content repeatedly leaves you feeling inadequate, mute it.',
      'They do not need to be wrong for the content to be wrong for you.',
    ],
    prompt: undefined,
  },
  {
    day: 25,
    category: 'For Mom',
    title: 'Feeling Guilty Doesn\'t Automatically Mean You Did Something Wrong',
    body: [
      'Rest? Guilt. Ask for help? Guilt. Want time alone? Guilt. Return to work? Guilt. Don\'t want to return? Somehow, guilt again.',
      'Guilt is a feeling, not always a verdict.',
      'Sometimes it points to something we genuinely want to repair. Sometimes it appears because mothers are surrounded by contradictory expectations.',
      'When guilt shows up, pause before obeying it.',
      'Ask: did I actually do something wrong, or do I simply feel guilty?',
      'Those are different questions.',
    ],
    prompt: undefined,
  },
  {
    day: 26,
    category: 'Practical',
    title: 'Visitors Should Leave Your House Lighter',
    body: [
      'A useful newborn-stage rule: good visitors reduce the workload.',
      'They can bring lunch, wash dishes, take out garbage, pick up groceries, entertain an older child, or simply sit with you without expecting hospitality.',
      'Holding the baby may be helpful too — if that is what you want.',
      'The test is simple: did the visit leave the household lighter or heavier?',
      'You are allowed to shape visits around what your family needs right now.',
    ],
    prompt: undefined,
  },
  {
    day: 27,
    category: 'For Mom',
    title: 'You\'re Allowed to Want Five Minutes Alone',
    body: [
      'Being needed constantly can feel beautiful and overwhelming.',
      'Someone needs your hands, attention, body, voice, or presence again and again.',
      'Wanting five minutes where nobody needs anything from you does not make you selfish.',
      'If your baby is safely cared for and it is possible, take a few minutes that are not for chores, organizing, or catching up.',
      'No productive use required.',
      'You do not have to earn a few minutes of being only yourself.',
    ],
    prompt: undefined,
  },
  {
    day: 28,
    category: 'Mental Load',
    title: 'Stop Being the Only One Who Knows',
    body: [
      'Where are the diapers? When is the appointment? Are we running low on wipes? What goes in the bag?',
      'When one person knows every answer, information itself becomes work.',
      'Shared calendars, lists, routines, and responsibilities are not just organization tools. They are ways of moving knowledge out of one person\'s head and into the household.',
      'Choose one thing only you currently know and put it somewhere shared.',
      'The goal is not for Mom to become the family\'s better database.',
      'The goal is for the family to stop requiring one.',
    ],
    prompt: undefined,
  },
  {
    day: 29,
    category: 'For Parents',
    title: 'Your Relationship May Feel Different Right Now',
    body: [
      'A baby can turn conversation into logistics: feeds, diapers, appointments, sleep, groceries, tomorrow.',
      'You may live beside someone and still miss them.',
      'Fatigue can also make small frustrations feel enormous. Resentment grows easily inside unspoken expectations.',
      'Try one conversation that is not an accusation. Ask, “What\'s been hardest for you this week?” Listen. Then switch.',
      'Before you finish, ask, “What\'s one thing I could take off your plate tomorrow?”',
      'You do not need to solve the whole relationship tonight. Staying curious about each other is enough for one conversation.',
    ],
    prompt: undefined,
  },
  {
    day: 30,
    category: 'Milestone',
    title: 'One Month: Don\'t Forget the Woman Who Was There',
    body: [
      'A month of photos may already exist — mostly of the baby.',
      'Today, notice the person who has been standing just outside the frame.',
      'What has become easier? What still feels hard? What are you carrying that someone else could carry? What do you need more of? What do you need less of?',
      'There is no score. This is not a performance review.',
      'Take a picture with your baby if you want to. Not because you look rested or because the house looks good.',
      'Take it because you were here too.',
    ],
    prompt: undefined,
  },
  {
    day: 31,
    category: 'Boundaries',
    title: 'You Don\'t Need Everyone\'s Advice',
    body: [
      'Family, friends, strangers, social media — everyone may seem to have discovered the correct way to raise a baby.',
      'Their correct ways will not always agree.',
      'Advice is input. It is not an instruction.',
      'For health and safety decisions, use reliable current guidance and qualified professionals. For the rest, you are allowed to consider advice, try something, reject it, or change your mind.',
      'A useful response to unsolicited advice is simply: “Thanks. I\'ll think about it.”',
      'Then you decide whether it deserves any more space in your head.',
    ],
    prompt: undefined,
  },
  {
    day: 32,
    category: 'Practical',
    title: 'Stop Rebuilding the Same Day From Scratch',
    body: [
      'Repeated decisions are expensive.',
      'What goes in the bag? What\'s for dinner? What do we need from the store? Who is handling that appointment?',
      'If you solve the same problem repeatedly, save the solution.',
      'Reuse the checklist. Keep five easy dinners. Save grocery staples. Create recurring reminders. Give recurring responsibilities a permanent owner.',
      'You do not need more discipline. You need fewer repeated decisions.',
      'Solve recurring problems once whenever you reasonably can.',
    ],
    prompt: undefined,
  },
  {
    day: 33,
    category: 'For Mom',
    title: 'Let Your Own Voice Into the Conversation',
    body: [
      'At first, nearly everything may have felt like a question.',
      'Now you have experience.',
      'You have watched patterns, tried things, adjusted, learned what works sometimes and what definitely does not.',
      'That does not mean you should stop asking for advice. It means your own observation now belongs in the discussion too.',
      'Before immediately asking someone else what they think, pause and ask: what do I think?',
      'Then gather whatever other information you need.',
      'Confidence is not knowing everything. It is trusting yourself to participate in the decision.',
    ],
    prompt: undefined,
  },
  {
    day: 34,
    category: 'Practical',
    title: 'Your To-Do List Needs Priorities, Not More Items',
    body: [
      'A long list makes “buy diapers” and “organize closet” look like equally unfinished obligations.',
      'They are not.',
      'Try three buckets: NOW, NEXT, LATER.',
      'Now is genuinely time-sensitive. Next matters soon. Later can wait without causing a problem.',
      'Later is not failure. It is prioritization.',
      'If everything is presented to your brain as urgent, your list becomes a source of pressure instead of a source of clarity.',
    ],
    prompt: undefined,
  },
  {
    day: 35,
    category: 'For Mom',
    title: 'Don\'t Disappear Into \'Mom\'',
    body: [
      'People ask about the baby because there is a brand-new person here.',
      'But there is another person we do not want to lose track of.',
      'Before motherhood, you had interests, friendships, ambitions, humour, preferences, music, work, hobbies, and things that had nothing to do with children.',
      'You do not have to “get yourself back.” Maybe you are becoming someone different.',
      'But motherhood can be part of your identity without consuming the whole thing.',
      'Do one small thing today that belongs to you, not to motherhood.',
    ],
    prompt: undefined,
  },
  {
    day: 36,
    category: 'Worth Knowing',
    title: 'Safe Sleep: Keep the Rule Simple',
    body: [
      'Sleep advice can become noisy quickly. For safety, use current guidance rather than trends.',
      'Health Canada recommends placing babies on their backs for every sleep in a flat, firm, clear sleep space such as a crib, cradle, or bassinet that meets current Canadian safety regulations. Soft items should stay out of the sleep space, and room-sharing is recommended for the first six months.',
      'You do not need to memorize every internet argument.',
      'Save the authoritative guidance somewhere easy to find and share it with anyone who cares for your baby.',
      'When safety information changes, update the source — not your anxiety.',
    ],
    prompt: undefined,
  },
  {
    day: 37,
    category: 'Practical',
    title: 'A Routine Should Serve Your Family',
    body: [
      'A good day can tempt you to recreate it exactly.',
      'But babies change, and yesterday is not a contract.',
      'Routines can reduce decisions and create useful rhythm. They become less useful when every deviation feels like failure.',
      'Keep the parts that help. Change the parts that do not.',
      'Instead of asking how to force today to look like yesterday, ask what would make today work reasonably well.',
    ],
    prompt: undefined,
  },
  {
    day: 38,
    category: 'Mental Load',
    title: 'Your Brain Is Not a Storage System',
    body: [
      '“I need to remember...” is a clue.',
      'The wipes. The question for the appointment. The form. The detergent. Saturday. The message.',
      'Each thought is small. Together they become dozens of open loops.',
      'Capture the thought somewhere you trust, give it a date or owner if it needs one, and let it leave your working memory.',
      'Good organization is not about becoming better at remembering everything.',
      'Good organization lets you forget safely.',
    ],
    prompt: undefined,
  },
  {
    day: 39,
    category: 'For Mom',
    title: 'Look Back Before You Decide You\'re Failing',
    body: [
      'Progress is hard to see from inside it.',
      'Your brain notices today\'s problem more readily than the problem that quietly stopped being a problem two weeks ago.',
      'Ask: what is easier now than it was then?',
      'Find one thing. Then another.',
      'This is not forced positivity. It is evidence.',
      'Difficult today does not mean nothing has changed.',
    ],
    prompt: undefined,
  },
  {
    day: 40,
    category: 'Practical',
    title: 'Make the System Fit the Life',
    body: [
      'If the same frustration keeps returning, treat it as a systems problem before treating it as a personal failure.',
      'What is repeatedly forgotten? Put it somewhere reliable.',
      'What causes arguments? Clarify ownership.',
      'What takes too many steps? Simplify it.',
      'What nobody actually cares about? Stop doing it.',
      'You do not need to become capable of doing everything. You can become better at deciding what deserves your energy.',
    ],
    prompt: undefined,
  },
  {
    day: 41,
    category: 'Boundaries',
    title: 'You Are Allowed to Have Boundaries',
    body: [
      'Becoming a mother did not make your time, body, home, or decisions public property.',
      'You can decline a visit, end a visit, change your mind, refuse to discuss a decision, or say that something does not work for your family.',
      'Keep a few phrases ready so you do not have to invent them while tired:',
      '“We\'re not up for visitors today.”',
      '“This is what works for us right now.”',
      '“I\'d rather not discuss that.”',
      'A boundary does not have to accuse anyone. Sometimes it simply protects what your household needs.',
    ],
    prompt: undefined,
  },
  {
    day: 42,
    category: 'Milestone',
    title: 'Six Weeks Is a Checkpoint, Not a Deadline',
    body: [
      'Six weeks can start sounding like a finish line long before it arrives.',
      'Bodies recover differently. Babies differ. Sleep, feeding, birth experiences, support, emotions, and circumstances differ.',
      'A postpartum appointment can be an important point of care, but it is not a graduation ceremony.',
      'Keep a running list of questions, symptoms, concerns, and changes you want to discuss. Do not rely on tired memory once you are in the room.',
      'Instead of asking, “Shouldn\'t I be further along?” ask, “How am I actually doing?”',
      'That is a much better question.',
    ],
    prompt: undefined,
  },
  {
    day: 43,
    category: 'For Mom',
    title: 'A Bad Hour Doesn\'t Need the Rest of Your Day',
    body: [
      'A hard hour can convince your brain that the whole day is ruined.',
      'Try being more precise.',
      'Maybe 10:00 to 11:00 was awful.',
      'That is not the same as the entire day.',
      'Reset wherever you are: eat, drink, change rooms, ask for help, step outside if practical, or simply say, “That was hard. Now we\'re here.”',
      'You do not have to wait for tomorrow morning to begin again.',
    ],
    prompt: undefined,
  },
  {
    day: 44,
    category: 'For Mom',
    title: 'Rest Is Not Something You Earn',
    body: [
      '“I\'ll rest when I\'m done” no longer works when the work cycles forever.',
      'There will be another bottle, another meal, another load, another message, another need.',
      'If rest comes only after everything else, rest may never arrive.',
      'When a quiet window appears, do not automatically ask what you can get done.',
      'Sometimes ask what you can stop doing.',
      'Rest is part of the system, not the prize at the end.',
    ],
    prompt: undefined,
  },
  {
    day: 45,
    category: 'Reflection',
    title: 'Ask What\'s Working, Not Whether You\'re Winning',
    body: [
      'Parenthood does not need a halfway scorecard.',
      'A better reflection is practical: what is working, what keeps frustrating you, what are you doing because you think you are supposed to, and what could someone else own?',
      'Keep what works.',
      'Change what repeatedly creates friction.',
      'Question what no longer matters.',
      'Hand off what does not specifically require you.',
      'Reflection should reduce future load, not create another standard you have to meet.',
    ],
    prompt: undefined,
  },
  {
    day: 46,
    category: 'Worth Knowing',
    title: 'Trust Yourself — and Ask for Help',
    body: [
      '“Trust your instincts” can be useful advice, but it should not become pressure to know everything yourself.',
      'You know your baby in ways other people do not. You notice patterns and changes.',
      'You can also be uncertain.',
      'Sometimes trusting yourself sounds like, “Something feels different and I want to ask about it.”',
      'You do not have to choose between trusting yourself and seeking professional help.',
      'Good judgment can include both.',
    ],
    prompt: undefined,
  },
  {
    day: 47,
    category: 'Mental Load',
    title: 'Don\'t Delegate Tasks. Share Ownership.',
    body: [
      'If you are always saying, “Can you change the baby?” “Can you wash these?” “Can you pick that up?” then another person may be doing tasks while you continue managing the operation.',
      'Ask instead: who owns this?',
      'Ownership includes noticing, remembering, planning, doing, and following through.',
      'Not every responsibility needs to be split evenly. It does need to be intentional enough that one person is not silently responsible for the entire system.',
    ],
    prompt: undefined,
  },
  {
    day: 48,
    category: 'For Mom',
    title: 'Put Something Down',
    body: [
      'You do not need another productivity hack today.',
      'You may need to stop doing something.',
      'An obligation. A household standard. A social commitment. A task you inherited because nobody else volunteered.',
      'Ask what actually happens if you stop doing it for a while.',
      'If the answer is “not much,” you may have found something worth dropping.',
      'Do not immediately fill the space with a replacement.',
    ],
    prompt: undefined,
  },
  {
    day: 49,
    category: 'For Parents',
    title: 'You\'re Allowed to Miss Each Other',
    body: [
      'Two people can live in the same house, care for the same baby, talk all day, and still miss each other.',
      'Much of the talking may be logistics.',
      'If it feels right, find ten minutes that are not about the baby, house, schedule, or grocery list.',
      'Ask something human: what have you been thinking about? What do you miss? What are you looking forward to?',
      'You are not trying to recreate your old relationship. You are learning how the relationship fits inside this new life.',
    ],
    prompt: undefined,
  },
  {
    day: 50,
    category: 'For Mom',
    title: 'Keep an Evidence List for Hard Days',
    body: [
      'Confidence does not have to depend on how confident you feel today.',
      'Keep evidence.',
      'Something you can do now that once intimidated you.',
      'Something you understand better.',
      'Something you asked for help with.',
      'Something difficult you got through.',
      'Something you changed because it was not working.',
      'On a hard day, feelings may tell you that you cannot handle anything.',
      'Evidence can remind you that you have figured out the next step before.',
    ],
    prompt: undefined,
  },
  {
    day: 51,
    category: 'Mental Load',
    title: 'You Don\'t Have to Solve Tomorrow Tonight',
    body: [
      'Night can turn tomorrow into an emergency.',
      'Groceries. Appointments. Messages. Weekend plans. Supplies. What if tonight is terrible?',
      'Capture what actually needs remembering, then let tomorrow remain tomorrow.',
      'Your brain needs a closing time.',
      'If something is safely stored in a system you trust, you are allowed to stop rehearsing it in bed.',
    ],
    prompt: undefined,
  },
  {
    day: 52,
    category: 'For Mom',
    title: 'Productivity Is a Terrible Measure of Your Worth',
    body: [
      'If productivity used to make you feel competent, newborn life can scramble the measurement.',
      'You can work all day and still see laundry, dishes, and unanswered messages.',
      'Care work also repeats. The baby needing another feed does not erase the previous one.',
      'Your value is not the number of visible outputs at the end of the day.',
      'Caregiving counts even when the evidence disappears quickly.',
    ],
    prompt: undefined,
  },
  {
    day: 53,
    category: 'For Mom',
    title: 'Bring Back One Tiny Piece of Yourself',
    body: [
      'You do not need a weekend away to reconnect with yourself.',
      'Start with one thread.',
      'A song. A favourite coffee. A friend. Two pages of a book. A hobby in miniature. A ridiculous podcast.',
      'The goal is not to restore your old life exactly.',
      'It is to remind yourself that you still exist inside this new one.',
    ],
    prompt: undefined,
  },
  {
    day: 54,
    category: 'Practical',
    title: 'Build a Reset Button',
    body: [
      'Some days need a reset, not a rescue.',
      'Choose a few things that reliably help you change the temperature of the day: food, water, fresh air, a shower, different clothes, music, calling someone, handing the baby to another safe caregiver for a few minutes.',
      'Your reset does not need to be impressive.',
      'It just needs to help you move from “everything is happening” to “here is the next thing.”',
    ],
    prompt: undefined,
  },
  {
    day: 55,
    category: 'For Mom',
    title: 'You Don\'t Have to Enjoy Every Minute',
    body: [
      '“Enjoy every minute” is impossible advice.',
      'Some moments are beautiful. Some are boring, painful, frustrating, lonely, or exhausting.',
      'Knowing a stage is temporary does not make every minute enjoyable.',
      'Try something smaller: notice some moments.',
      'A tiny hand. A strange noise. The weight of your baby sleeping against you. Someone making you laugh when you\'re both tired.',
      'You do not need to turn your entire life into a memory while you are still living it.',
    ],
    prompt: undefined,
  },
  {
    day: 56,
    category: 'Reflection',
    title: 'Notice What Became Familiar',
    body: [
      'Think about something that once required your full concentration.',
      'Now it may be ordinary.',
      'Familiar is not the same as easy, but familiarity matters. It means your brain is spending less energy on something that was once completely new.',
      'Look for one ordinary thing today and remember that there was a first time you did it.',
      'That is what learning often looks like: eventually, your brain stops announcing it.',
    ],
    prompt: undefined,
  },
  {
    day: 57,
    category: 'Mental Load',
    title: 'The Mental Load Is More Than Chores',
    body: [
      'Buying diapers is a task.',
      'Noticing they are low, remembering the size, knowing where to get them, adding them to the list, buying them before they run out, and anticipating the next size is the mental load around the task.',
      'Now multiply that by food, appointments, clothes, messages, bills, supplies, childcare, family plans, and forms.',
      'Do not only divide chores.',
      'Divide noticing, remembering, planning, and follow-through too.',
    ],
    prompt: undefined,
  },
  {
    day: 58,
    category: 'Practical',
    title: 'Use a Trusted Place for \'Don\'t Forget\'',
    body: [
      'A reminder system only reduces mental load if your brain trusts it.',
      'When something appears in your head, capture it once. Give it a date, a person, a list, or a place.',
      'Then stop rehearsing it.',
      'If your system is so complicated that you also have to remember to manage the system, simplify the system.',
      'The best reminder is one you do not have to recreate twice.',
    ],
    prompt: undefined,
  },
  {
    day: 59,
    category: 'For Mom',
    title: 'Touched Out Is a Real Need for Space',
    body: [
      'After hours of holding, feeding, rocking, comforting, and being physically needed, you may want nobody to touch you for a while.',
      'That does not automatically mean something is wrong with your relationship.',
      'Say it before resentment has to say it for you: “I love you. I\'m touched out right now and need a little space.”',
      'For a partner or support person, sometimes the most loving offer is not more affection. It is twenty minutes where nobody needs anything from her.',
    ],
    prompt: undefined,
  },
  {
    day: 60,
    category: 'Milestone',
    title: 'Two Months: Build the Life, Not the Perfect Routine',
    body: [
      'By now, some systems have probably formed — deliberately or accidentally.',
      'Ask what is working surprisingly well. Protect it.',
      'What creates the same frustration every week? Change the system.',
      'What are you constantly reminding people about? Move the responsibility.',
      'What do you keep forgetting? Give it somewhere reliable to live.',
      'What are you doing that nobody actually cares about? Stop.',
      'And what do you miss about yourself? Bring back a small piece.',
      'The goal is not to become better at everything. It is to make the next month more livable.',
    ],
    prompt: undefined,
  },
  {
    day: 61,
    category: 'For Mom',
    title: 'You Know What Your Baby Needs. What Do You Need?',
    body: [
      'You have become practiced at scanning another person.',
      'Hungry? Tired? Uncomfortable? Needs closeness?',
      'Now turn some of that attention inward.',
      'Are you hungry? Exhausted? Lonely? Overstimulated? In need of company, quiet, help, or a change of scenery?',
      'Your needs are not interruptions to family life.',
      'They are part of family life.',
    ],
    prompt: undefined,
  },
  {
    day: 62,
    category: 'For Mom',
    title: 'You\'re Allowed to Have Fun',
    body: [
      'A free moment does not automatically belong to cleaning, catching up, or self-improvement.',
      'You are still allowed to enjoy things for no productive reason.',
      'Watch the silly show. Play music. Call the friend. Eat something you love. Laugh.',
      'Joy does not need to justify itself.',
      'You are a person, not a household maintenance system.',
    ],
    prompt: undefined,
  },
  {
    day: 63,
    category: 'For Mom',
    title: 'Notice an Ordinary Moment',
    body: [
      'The ordinary details are often what disappear first.',
      'The chair you always sit in. The little noise your baby makes. The light in the room. The clothes that suddenly look too small.',
      'You do not need to photograph or post every moment.',
      'Just notice one.',
      '“This is what our life looks like right now.”',
      'That is enough.',
    ],
    prompt: undefined,
  },
  {
    day: 64,
    category: 'For Mom',
    title: 'You Don\'t Need Permission to Make This Easier',
    body: [
      'If grocery delivery helps, use it. If prepared food helps, buy it. If a simpler routine works, use the simpler routine. If someone trustworthy can help, accept the help.',
      'Difficulty is not proof of devotion.',
      'Ask what outcome you are actually trying to achieve, then find a safe, sustainable way to achieve it.',
      'Motherhood does not become more meaningful because you made yourself unnecessarily exhausted.',
    ],
    prompt: undefined,
  },
  {
    day: 65,
    category: 'For Mom',
    title: 'Convenience Is Not a Character Flaw',
    body: [
      'Sometimes convenience buys something more valuable than the task itself costs.',
      'Twenty minutes sitting down. A calmer evening. Food actually eaten. Less arguing. One fewer decision.',
      'When you reject an easier option, ask what you are trying to prove.',
      'If there is no good answer, choose easier.',
    ],
    prompt: undefined,
  },
  {
    day: 66,
    category: 'For Mom',
    title: 'Your Family Doesn\'t Need to Look Like Anyone Else\'s',
    body: [
      'Families have different babies, money, work schedules, support networks, cultures, homes, bodies, and energy.',
      '“What does everyone else do?” is often the wrong question.',
      'For health and safety, use reliable guidance.',
      'For many other choices, ask: is this safe, sustainable, and working for the people who actually live here?',
      'Your family is allowed to fit itself.',
    ],
    prompt: undefined,
  },
  {
    day: 67,
    category: 'Boundaries',
    title: 'You Don\'t Have to Defend Every Decision',
    body: [
      'Some questions are invitations to debate.',
      '“You\'re doing it that way?”',
      '“We never did that.”',
      '“Are you sure?”',
      'You do not have to attend every debate.',
      'Try: “This is what works for us.” Or: “We\'ve looked into it and we\'re comfortable with the decision.”',
      'Then change the subject.',
      'Save your energy for decisions that still need making.',
    ],
    prompt: undefined,
  },
  {
    day: 68,
    category: 'For Mom',
    title: 'You Can Be Grateful and Exhausted',
    body: [
      'Gratitude should not become an eraser.',
      'You can love your baby and need a break. Be thankful and overwhelmed. Feel lucky and exhausted.',
      'Try replacing “but” with “and.”',
      '“I am grateful, and I am tired.”',
      'Two truths can exist together without one invalidating the other.',
    ],
    prompt: undefined,
  },
  {
    day: 69,
    category: 'For Mom',
    title: 'Overwhelmed Is Not the Same as Failing',
    body: [
      'When everything feels like too much, your brain may conclude that you are bad at this.',
      'Try a different diagnosis: perhaps there is simply too much happening at once.',
      'What can wait? What can be cancelled? What can someone else own? What can become easier? What does not actually matter?',
      'Before asking how Mom can cope better, ask what can be removed.',
      'Sometimes the answer is not more resilience. It is less load.',
    ],
    prompt: undefined,
  },
  {
    day: 70,
    category: 'Reflection',
    title: 'You\'ve Learned Someone Who Can\'t Explain Themselves',
    body: [
      'You have been learning a person who cannot simply tell you what they need.',
      'You have watched sounds, movements, expressions, patterns, crying, and quiet. You have tried something, watched, adjusted, and tried again.',
      'You will not interpret every signal perfectly. That is not the standard.',
      'Notice what you understand now that you did not understand before.',
      'Knowing your baby is not eliminating uncertainty. It is learning how to pay attention.',
    ],
    prompt: undefined,
  },
  {
    day: 71,
    category: 'Mental Load',
    title: 'Being Good at Carrying It Doesn\'t Mean You Should',
    body: [
      'Competent people get handed things.',
      'You remember, notice, organize, and get things done — so gradually more becomes yours.',
      'A household can look functional while one person quietly carries too much of it.',
      'Ask: if I stopped remembering this, would anyone else notice?',
      'Your competence should not become the reason everyone else gets to think less.',
      '“Mom can handle it” and “Mom should handle it” are completely different statements.',
    ],
    prompt: undefined,
  },
  {
    day: 72,
    category: 'For Mom',
    title: 'You Don\'t Need to Catch Up',
    body: [
      'Catch up to what?',
      'Your life changed. Your responsibilities changed. Your time and energy changed.',
      'Some old expectations may still matter. Others may no longer deserve the same priority.',
      'When you hear yourself saying you need to catch up, ask whether the thing still belongs in the life you have now.',
      'Reprioritizing is not falling behind.',
    ],
    prompt: undefined,
  },
  {
    day: 73,
    category: 'Practical',
    title: 'Make the Easy Things Automatic',
    body: [
      'Do not spend premium attention on maintenance if a safe, simple system can handle it.',
      'Recurring reminders. Shared lists. Automatic payments. Saved grocery staples. Repeat tasks. Default routines.',
      'Find one thing you have manually remembered several times and ask why you are still remembering it.',
      'Automate it, assign it, schedule it, or eliminate it.',
    ],
    prompt: undefined,
  },
  {
    day: 74,
    category: 'For Mom',
    title: 'You Are Not Behind',
    body: [
      'Another family may have a routine you do not. Another mother may be exercising, working, travelling, or looking remarkably composed online.',
      'You are not all running the same course.',
      'When you think, “I should be...” finish the sentence and ask: according to whom?',
      'Sometimes there is a real need. Sometimes there is only an expectation you never consciously chose.',
    ],
    prompt: undefined,
  },
  {
    day: 75,
    category: 'For Mom',
    title: 'Your Body Isn\'t an Unfinished Project',
    body: [
      'Your body may look, feel, and move differently after pregnancy and birth.',
      'You do not have to pretend to love every change. You also do not have to treat your body as a problem that needs urgently fixing.',
      'Instead of asking how to get your old body back, ask what your body needs now: appropriate medical care, food, rest, patience, comfortable clothes, or movement that is right for you.',
      'Your body is where you live, not a deadline.',
    ],
    prompt: undefined,
  },
  {
    day: 76,
    category: 'Mental Load',
    title: 'Ask for the Whole Thing',
    body: [
      '“Can you grab milk?” solves milk.',
      '“Can you own groceries this week?” removes a category of responsibility.',
      'Small requests solve small tasks. Ownership can remove mental load.',
      'When you ask for help, notice whether you really need another pair of hands or another brain carrying responsibility.',
      'Sometimes the better request is: “Can you take care of this whole thing?”',
    ],
    prompt: undefined,
  },
  {
    day: 77,
    category: 'For Mom',
    title: 'You\'re Allowed to Change Your Mind',
    body: [
      'Before the baby arrived, you probably had plans and strong opinions.',
      'Then an actual baby arrived.',
      'Changing your mind can mean you learned something you could not have known before.',
      'A plan made with less information does not deserve loyalty simply because you made it first.',
      '“This isn\'t working. We\'re changing it” is a perfectly respectable parenting sentence.',
    ],
    prompt: undefined,
  },
  {
    day: 78,
    category: 'For Mom',
    title: 'Protect Something That Belongs to You',
    body: [
      'Motherhood can expand into every available space.',
      'Choose something small that remains yours: a walk, a class, coffee alone, a hobby, a phone call, a corner of the house, twenty minutes at a predictable time.',
      'You are not rejecting your family.',
      'You are remembering that you are part of the family too.',
    ],
    prompt: undefined,
  },
  {
    day: 79,
    category: 'For Mom',
    title: 'Let Good Enough Save You',
    body: [
      'Perfect is expensive.',
      'It costs time, attention, energy, and often peace.',
      'Many parts of family life do not need the best possible solution. They need a safe, reasonable one that works.',
      'Choose one thing that usually gets too much of your energy and deliberately do the good-enough version.',
      'Then stop.',
      'Good enough is not always settling. Sometimes it is wisdom.',
    ],
    prompt: undefined,
  },
  {
    day: 80,
    category: 'Reflection',
    title: 'You Don\'t Need Every Answer Before the Question Arrives',
    body: [
      'There will always be another thing you have not done before.',
      'That is not evidence that you are unprepared. It is part of raising a changing human being.',
      'Think about what you once did not know and now handle without much thought.',
      'Then name something you still do not know.',
      'Let it exist without immediately fixing it.',
      'The last few months have already shown you something useful: you can learn, ask, adjust, and find the next step when it becomes relevant.',
    ],
    prompt: undefined,
  },
  {
    day: 81,
    category: 'Practical',
    title: 'You Don\'t Have to Remember Everything',
    body: [
      'Responsibility does not require storing everything in your own head.',
      'Appointments can live in the calendar. Groceries can live on the list. Questions for a clinician can live in a note. Tasks can belong to someone else. Reminders can happen automatically.',
      'Every time you think, “I need to remember...” capture it somewhere trustworthy.',
      'Then practice saying, “I don\'t need to remember this anymore.”',
      'The goal is not helping Mom remember more. It is giving her fewer things she needs to remember at all.',
    ],
    prompt: undefined,
  },
  {
    day: 82,
    category: 'Mental Load',
    title: 'You Don\'t Have to Be the Default Answer',
    body: [
      'When one person knows the answers, every question starts flowing toward them.',
      'Where is it? When is it? What do we need? What should I do?',
      'Being knowledgeable does not mean every question should become yours.',
      'Sometimes the answer is: “It\'s in the calendar.” “Check the list.” “You\'re handling that one.” Or simply, “I don\'t know — can you figure it out?”',
      'A capable household should not require one person to function as the information desk.',
    ],
    prompt: undefined,
  },
  {
    day: 83,
    category: 'For Mom',
    title: 'Make Room for the Version of You That\'s Emerging',
    body: [
      'There is a lot of pressure to “feel like yourself again.”',
      'But what if the goal is not to go backward?',
      'Some old parts of you may return exactly as they were. Some priorities may change. You may become more protective of your time, less interested in pleasing people, more ambitious, quieter, softer, or simply different.',
      'You do not have to decide who motherhood has made you.',
      'Ask instead: what feels like me right now?',
      'Follow that.',
    ],
    prompt: undefined,
  },
  {
    day: 84,
    category: 'For Mom',
    title: 'Some Things Can Just Be Easier',
    body: [
      'Not every problem needs optimization.',
      'Dinner can be sandwiches. Laundry can stay in the basket. A plan can be cancelled. Someone else can do it. A system that already works can remain unimproved.',
      'Before improving something, ask whether it actually needs improving.',
      'Some things do not need to be better.',
      'They just need to work.',
    ],
    prompt: undefined,
  },
  {
    day: 85,
    category: 'For Mom',
    title: 'Your Baby Doesn\'t Need a Perfect Mother',
    body: [
      'You will misunderstand something, forget something, lose patience, change your mind, and make decisions you later revisit.',
      'That is not a warning. It is being human while raising another human.',
      'A better standard than perfection is: pay attention, keep learning, repair when needed, ask questions, use reliable guidance when it matters, and change course when new information tells you to.',
      'Your baby does not need a flawless performance.',
      'They need a real person who keeps showing up.',
    ],
    prompt: undefined,
  },
  {
    day: 86,
    category: 'Mental Load',
    title: 'Let Someone Else Notice',
    body: [
      'Sometimes the exhausting part is not doing the task. It is being the person who always notices first.',
      'The empty container. The garbage. The appointment. The clothes that no longer fit. The form on the counter.',
      'Where appropriate, stop rescuing the system before anyone else can see it.',
      'Make ownership clear and allow another capable adult to carry the attention too.',
      'Shared responsibility requires shared noticing, not only shared effort.',
    ],
    prompt: undefined,
  },
  {
    day: 87,
    category: 'For Mom',
    title: 'Take the Picture With You in It',
    body: [
      'Mothers often become the photographers of family life.',
      'The camera roll fills with the baby and the baby with everyone else.',
      'Hand someone else the phone.',
      'Get in the picture even if your hair is messy, the room is imperfect, or you do not feel photo-ready.',
      'The picture does not need to prove that you looked good.',
      'It can simply prove that you were there.',
    ],
    prompt: undefined,
  },
  {
    day: 88,
    category: 'Practical',
    title: 'Ask What Your Family Can Stop Doing',
    body: [
      'Families talk constantly about what to add: a better routine, another system, another activity.',
      'Ask the opposite question.',
      'What can we stop?',
      'Does this matter? Who does it matter to? What happens if we stop? Would anyone genuinely miss it?',
      'A good family system does not only organize more.',
      'It identifies what should not be there at all.',
    ],
    prompt: undefined,
  },
  {
    day: 89,
    category: 'Reflection',
    title: 'Put the Mental Load on the Table',
    body: [
      'Imagine everything in your head sitting on a table.',
      'Appointments. Groceries. Worries. Messages. Research. Household tasks. Someone else\'s reminder. Next week.',
      'Take each item and ask three questions:',
      'Does this need to be mine?',
      'Does this need my attention today?',
      'Does this need to exist at all?',
      'Then decide: do it, schedule it, give it away, or delete it.',
      'Stop carrying undecided work simply because it entered your head.',
    ],
    prompt: undefined,
  },
  {
    day: 90,
    category: 'For Mom',
    title: 'Look at What Has Changed',
    body: [
      'There probably was not one moment when you suddenly felt like you knew what you were doing.',
      'It happened quietly.',
      'Something that once made you nervous became ordinary. A sound became familiar. Your hands learned things. You discovered which advice helps, what kind of support actually supports you, and which expectations are not worth carrying.',
      'You learned about your baby. You also learned about yourself.',
      'Maybe you discovered that you are stronger than you thought. Maybe you discovered that you do not always want to be strong. Maybe your priorities changed. Maybe your boundaries did too.',
      'There will be more firsts. More questions. More stages.',
      'You do not need all the answers now.',
      'You can learn. You can ask. You can adjust. You can change your mind. You can get help. You can put something down.',
      'Do not turn today into another list of ways to improve.',
      'Notice something you do not want to forget. Take a picture if you want one. Do something kind for yourself.',
      'Then keep living.',
      'MamaHQ is here for what comes next too.',
      'Post-audit product notes',
      'Hide the machinery — The 90-day sequence is for relevance and personalization. Avoid “ten days left,” “halfway,” “finish the journey,” or other program language.',
      'Use natural milestones — One week, two weeks, one month, six weeks, two months, and the transition around three months can feel meaningful. Arbitrary tens should not become celebrations.',
      'Content should become action — Where appropriate, connect an article to a small product action: save a question, assign ownership, add a reminder, create a leaving-home checklist, save a boundary response, or put something on a shared list.',
      'Do not optimize Mom into a better household manager — The product should redistribute, automate, remember, simplify, or eliminate work. The goal is not to help Mom carry more efficiently.',
      'Partner content must be contextual — Only surface partner-specific content when relevant. Use “partner or support person” when possible and never imply every mother has an available co-parent.',
      'Clinical content needs a verified layer — Store authoritative source, jurisdiction, review status, and last-reviewed date. AI may summarize verified guidance but should not invent the underlying recommendation.',
      'Avoid fake intimacy — Personalization should come from things Mom actually told MamaHQ. Remember and return meaningful information rather than manufacturing familiarity.',
      'Protect variety — The collection should rotate emotional support, practical systems, mental load, identity, relationships, boundaries, safety, and reflection so the feed never feels like 90 versions of the same reassurance.',
    ],
    prompt: undefined,
  },
]

// Day 1..90 -> its entry, for O(1) lookup by day number.
export const DAILY_READS: Record<number, DailyRead> = Object.fromEntries(
  ALL_READS.map((r) => [r.day, r]),
)

/** Estimated read time in minutes (>=1), ~200 wpm over title+body+prompt. */
export function readMinutes(r: DailyRead): number {
  const words = [r.title, ...r.body, r.prompt ?? ''].join(' ').trim().split(/\s+/).length
  return Math.max(1, Math.round(words / 200))
}

/** The read for a given day number, with graceful Day 91+ fallback to Day 90. */
export function pickDailyRead(day: number): DailyRead {
  if (day >= 1 && day <= 90 && DAILY_READS[day]) return DAILY_READS[day]
  return DAILY_READS[90]
}
