import type { CanonicalItem } from '../types.ts'
import { item } from './_helper.ts'

const B = { department: 'food', category: 'bakery', shopping_category: 'bakery', storage_type: 'ambient' } as const
const DELI = { department: 'food', category: 'deli', shopping_category: 'deli', storage_type: 'refrigerated' } as const

export const BAKERY_DELI: CanonicalItem[] = [
  /* --------------------------------- BAKERY -------------------------------- */
  item({ ...B, canonical_id: 'food.bakery.bread.bread', canonical_name: 'Bread', default_display_name: 'Bread', subcategory: 'bread', default_unit: 'loaf', allowed_units: ['loaf', 'each', 'bag'], search_priority: 90, tags: ['breakfast', 'sandwich', 'staple'], attributes: [{ attribute_id: 'bread.style' }] }),
  item({ ...B, canonical_id: 'food.bakery.bread.whole_wheat_bread', canonical_name: 'Whole Wheat Bread', default_display_name: 'Whole wheat bread', subcategory: 'bread', parent_concept_id: 'food.bakery.bread.bread', default_unit: 'loaf', allowed_units: ['loaf', 'bag'], tags: ['sandwich', 'staple'], attributes: [{ attribute_id: 'bread.style' }] }),
  item({ ...B, canonical_id: 'food.bakery.bread.white_bread', canonical_name: 'White Bread', default_display_name: 'White bread', subcategory: 'bread', parent_concept_id: 'food.bakery.bread.bread', default_unit: 'loaf', allowed_units: ['loaf', 'bag'], tags: ['sandwich'], attributes: [{ attribute_id: 'bread.style' }] }),
  item({ ...B, canonical_id: 'food.bakery.bread.sourdough', canonical_name: 'Sourdough Bread', default_display_name: 'Sourdough bread', subcategory: 'bread', parent_concept_id: 'food.bakery.bread.bread', default_unit: 'loaf', allowed_units: ['loaf'], tags: ['sandwich'] }),
  item({ ...B, canonical_id: 'food.bakery.bagels.bagels', canonical_name: 'Bagels', default_display_name: 'Bagels', subcategory: 'bagels', default_unit: 'bag', allowed_units: ['bag', 'package', 'each'], search_priority: 74, tags: ['breakfast'] }),
  item({ ...B, canonical_id: 'food.bakery.buns_rolls.hamburger_buns', canonical_name: 'Hamburger Buns', default_display_name: 'Hamburger buns', subcategory: 'buns_rolls', default_unit: 'package', allowed_units: ['package', 'bag'], tags: ['dinner', 'summer'], aliases: [{ alias: 'burger buns', type: 'synonym' }] }),
  item({ ...B, canonical_id: 'food.bakery.buns_rolls.hot_dog_buns', canonical_name: 'Hot Dog Buns', default_display_name: 'Hot dog buns', subcategory: 'buns_rolls', default_unit: 'package', allowed_units: ['package', 'bag'], tags: ['dinner', 'summer'] }),
  item({ ...B, canonical_id: 'food.bakery.buns_rolls.dinner_rolls', canonical_name: 'Dinner Rolls', default_display_name: 'Dinner rolls', subcategory: 'buns_rolls', default_unit: 'package', allowed_units: ['package', 'bag'], tags: ['dinner'] }),
  item({ ...B, canonical_id: 'food.bakery.tortillas_flatbread.tortillas', canonical_name: 'Tortillas', default_display_name: 'Tortillas', subcategory: 'tortillas_flatbread', default_unit: 'package', allowed_units: ['package', 'bag'], search_priority: 72, tags: ['dinner', 'wrap'], attributes: [{ attribute_id: 'tortilla.type' }] }),
  item({ ...B, canonical_id: 'food.bakery.tortillas_flatbread.pita', canonical_name: 'Pita Bread', default_display_name: 'Pita bread', subcategory: 'tortillas_flatbread', default_unit: 'package', allowed_units: ['package', 'bag'], tags: ['sandwich', 'wrap'] }),
  item({ ...B, canonical_id: 'food.bakery.tortillas_flatbread.naan', canonical_name: 'Naan', default_display_name: 'Naan', subcategory: 'tortillas_flatbread', default_unit: 'package', allowed_units: ['package'], tags: ['dinner'] }),
  item({ ...B, canonical_id: 'food.bakery.sweet_bakery.muffins', canonical_name: 'Muffins', default_display_name: 'Muffins', subcategory: 'sweet_bakery', default_unit: 'package', allowed_units: ['package', 'each'], tags: ['breakfast', 'snack'] }),
  item({ ...B, canonical_id: 'food.bakery.sweet_bakery.croissants', canonical_name: 'Croissants', default_display_name: 'Croissants', subcategory: 'sweet_bakery', default_unit: 'package', allowed_units: ['package', 'each'], tags: ['breakfast'] }),
  item({ ...B, canonical_id: 'food.bakery.sweet_bakery.donuts', canonical_name: 'Donuts', default_display_name: 'Donuts', subcategory: 'sweet_bakery', default_unit: 'box', allowed_units: ['box', 'each', 'package'], tags: ['snack', 'dessert'], aliases: [{ alias: 'doughnuts', type: 'synonym' }] }),
  item({ ...B, canonical_id: 'food.bakery.sweet_bakery.cake', canonical_name: 'Cake', default_display_name: 'Cake', subcategory: 'sweet_bakery', default_unit: 'each', allowed_units: ['each'], tags: ['dessert', 'party'] }),
  item({ ...B, canonical_id: 'food.bakery.sweet_bakery.pie', canonical_name: 'Pie', default_display_name: 'Pie', subcategory: 'sweet_bakery', default_unit: 'each', allowed_units: ['each'], tags: ['dessert'] }),
  item({ ...B, canonical_id: 'food.bakery.sweet_bakery.cookies_bakery', canonical_name: 'Bakery Cookies', default_display_name: 'Bakery cookies', subcategory: 'sweet_bakery', default_unit: 'package', allowed_units: ['package', 'box'], tags: ['dessert', 'snack'] }),
  item({ ...B, canonical_id: 'food.bakery.bread.english_muffins', canonical_name: 'English Muffins', default_display_name: 'English muffins', subcategory: 'bread', default_unit: 'package', allowed_units: ['package'], tags: ['breakfast'] }),

  /* ---------------------------------- DELI --------------------------------- */
  item({ ...DELI, canonical_id: 'food.deli.deli_meat.deli_ham', canonical_name: 'Deli Ham', default_display_name: 'Deli ham', subcategory: 'deli_meat', default_unit: 'package', allowed_units: ['package', 'g', 'lb'], search_priority: 70, tags: ['sandwich', 'lunch', 'deli'], aliases: [{ alias: 'sliced ham', type: 'synonym' }] }),
  item({ ...DELI, canonical_id: 'food.deli.deli_meat.deli_turkey', canonical_name: 'Deli Turkey', default_display_name: 'Deli turkey', subcategory: 'deli_meat', default_unit: 'package', allowed_units: ['package', 'g', 'lb'], search_priority: 70, tags: ['sandwich', 'lunch', 'deli'], aliases: [{ alias: 'sliced turkey', type: 'synonym' }, { alias: 'turkey breast slices', type: 'synonym' }] }),
  item({ ...DELI, canonical_id: 'food.deli.deli_meat.salami', canonical_name: 'Salami', default_display_name: 'Salami', subcategory: 'deli_meat', default_unit: 'package', allowed_units: ['package', 'g'], tags: ['sandwich', 'deli'] }),
  item({ ...DELI, canonical_id: 'food.deli.deli_meat.pepperoni', canonical_name: 'Pepperoni', default_display_name: 'Pepperoni', subcategory: 'deli_meat', default_unit: 'package', allowed_units: ['package', 'g'], tags: ['pizza', 'snack'] }),
  item({ ...DELI, canonical_id: 'food.deli.deli_meat.bologna', canonical_name: 'Bologna', default_display_name: 'Bologna', subcategory: 'deli_meat', default_unit: 'package', allowed_units: ['package', 'g'], tags: ['sandwich', 'lunch'] }),
  item({ ...DELI, canonical_id: 'food.deli.prepared_deli.rotisserie_chicken', canonical_name: 'Rotisserie Chicken', default_display_name: 'Rotisserie chicken', subcategory: 'prepared_deli', default_unit: 'each', allowed_units: ['each'], search_priority: 74, tags: ['dinner', 'prepared'] }),
  item({ ...DELI, canonical_id: 'food.deli.prepared_deli.hummus', canonical_name: 'Hummus', default_display_name: 'Hummus', subcategory: 'prepared_deli', default_unit: 'tub', allowed_units: ['tub', 'package', 'g'], tags: ['snack', 'dip'] }),
  item({ ...DELI, canonical_id: 'food.deli.prepared_deli.olives', canonical_name: 'Olives', default_display_name: 'Olives', subcategory: 'prepared_deli', default_unit: 'jar', allowed_units: ['jar', 'can'], tags: ['snack', 'deli'] }),
  item({ ...DELI, canonical_id: 'food.deli.prepared_deli.potato_salad', canonical_name: 'Potato Salad', default_display_name: 'Potato salad', subcategory: 'prepared_deli', default_unit: 'tub', allowed_units: ['tub'], tags: ['prepared', 'summer'] }),
  item({ ...DELI, canonical_id: 'food.deli.prepared_deli.coleslaw', canonical_name: 'Coleslaw', default_display_name: 'Coleslaw', subcategory: 'prepared_deli', default_unit: 'tub', allowed_units: ['tub'], tags: ['prepared', 'summer'] }),
]
