import type { CanonicalItem } from '../types.ts'
import { item } from './_helper.ts'

const B = { department: 'food', category: 'beverages', shopping_category: 'beverages', storage_type: 'ambient' } as const
const CT = { department: 'food', category: 'coffee_tea', shopping_category: 'beverages', storage_type: 'ambient' } as const

export const BEVERAGES: CanonicalItem[] = [
  item({ ...B, canonical_id: 'food.beverages.water.bottled_water', canonical_name: 'Bottled Water', default_display_name: 'Bottled water', subcategory: 'water', default_unit: 'case', allowed_units: ['case', 'bottle', 'L'], search_priority: 76, tags: ['drink', 'staple'], aliases: [{ alias: 'water', type: 'colloquial' }] }),
  item({ ...B, canonical_id: 'food.beverages.water.sparkling_water', canonical_name: 'Sparkling Water', default_display_name: 'Sparkling water', subcategory: 'water', default_unit: 'case', allowed_units: ['case', 'bottle', 'can'], tags: ['drink'], aliases: [{ alias: 'club soda', type: 'synonym' }, { alias: 'soda water', type: 'synonym' }] }),
  item({ ...B, canonical_id: 'food.beverages.soft_drink.soda', canonical_name: 'Soda', default_display_name: 'Soda', subcategory: 'soft_drink', default_unit: 'case', allowed_units: ['case', 'bottle', 'can', 'L'], search_priority: 74, tags: ['drink'], aliases: [{ alias: 'pop', type: 'regional', locale: 'en-CA' }, { alias: 'soft drink', type: 'synonym' }, { alias: 'soda pop', type: 'colloquial' }] }),
  item({ ...B, canonical_id: 'food.beverages.soft_drink.cola', canonical_name: 'Cola', default_display_name: 'Cola', subcategory: 'soft_drink', parent_concept_id: 'food.beverages.soft_drink.soda', default_unit: 'case', allowed_units: ['case', 'bottle', 'can'], tags: ['drink'] }),
  item({ ...B, canonical_id: 'food.beverages.soft_drink.ginger_ale', canonical_name: 'Ginger Ale', default_display_name: 'Ginger ale', subcategory: 'soft_drink', parent_concept_id: 'food.beverages.soft_drink.soda', default_unit: 'case', allowed_units: ['case', 'bottle', 'can'], tags: ['drink'] }),
  item({ ...B, canonical_id: 'food.beverages.juice.orange_juice', canonical_name: 'Orange Juice', default_display_name: 'Orange juice', subcategory: 'juice', default_unit: 'carton', allowed_units: ['carton', 'bottle', 'L'], search_priority: 78, tags: ['drink', 'breakfast'], aliases: [{ alias: 'oj', type: 'abbreviation' }], attributes: [{ attribute_id: 'juice.flavour' }] }),
  item({ ...B, canonical_id: 'food.beverages.juice.apple_juice', canonical_name: 'Apple Juice', default_display_name: 'Apple juice', subcategory: 'juice', default_unit: 'bottle', allowed_units: ['bottle', 'carton', 'L'], search_priority: 74, tags: ['drink', 'kids'], attributes: [{ attribute_id: 'juice.flavour' }] }),
  item({ ...B, canonical_id: 'food.beverages.juice.juice_boxes', canonical_name: 'Juice Boxes', default_display_name: 'Juice boxes', subcategory: 'juice', default_unit: 'pack', allowed_units: ['pack', 'box'], tags: ['drink', 'kids', 'school_lunch'] }),
  item({ ...B, canonical_id: 'food.beverages.juice.cranberry_juice', canonical_name: 'Cranberry Juice', default_display_name: 'Cranberry juice', subcategory: 'juice', default_unit: 'bottle', allowed_units: ['bottle'], tags: ['drink'] }),
  item({ ...B, canonical_id: 'food.beverages.sports_energy.sports_drink', canonical_name: 'Sports Drink', default_display_name: 'Sports drink', subcategory: 'sports_energy', default_unit: 'bottle', allowed_units: ['bottle', 'case'], tags: ['drink'], aliases: [{ alias: 'gatorade', type: 'colloquial' }] }),
  item({ ...B, canonical_id: 'food.beverages.sports_energy.energy_drink', canonical_name: 'Energy Drink', default_display_name: 'Energy drink', subcategory: 'sports_energy', default_unit: 'can', allowed_units: ['can', 'case'], tags: ['drink'] }),
  item({ ...B, canonical_id: 'food.beverages.drink_mix.drink_crystals', canonical_name: 'Drink Mix', default_display_name: 'Drink mix', subcategory: 'drink_mix', default_unit: 'box', allowed_units: ['box', 'package'], tags: ['drink', 'kids'], aliases: [{ alias: 'kool-aid', type: 'colloquial' }, { alias: 'powdered drink mix', type: 'synonym' }] }),
  item({ ...B, canonical_id: 'food.beverages.juice.lemonade', canonical_name: 'Lemonade', default_display_name: 'Lemonade', subcategory: 'juice', default_unit: 'bottle', allowed_units: ['bottle', 'carton'], tags: ['drink', 'summer'] }),
  item({ ...B, canonical_id: 'food.beverages.soft_drink.iced_tea', canonical_name: 'Iced Tea', default_display_name: 'Iced tea', subcategory: 'soft_drink', default_unit: 'bottle', allowed_units: ['bottle', 'case', 'carton'], tags: ['drink', 'summer'] }),

  /* ------------------------------ COFFEE & TEA ----------------------------- */
  item({ ...CT, canonical_id: 'food.coffee_tea.coffee.coffee', canonical_name: 'Coffee', default_display_name: 'Coffee', subcategory: 'coffee', default_unit: 'bag', allowed_units: ['bag', 'box', 'g', 'can'], search_priority: 84, tags: ['drink', 'staple', 'coffee'], attributes: [{ attribute_id: 'coffee.roast' }, { attribute_id: 'coffee.format', typical: true }] }),
  item({ ...CT, canonical_id: 'food.coffee_tea.coffee.coffee_pods', canonical_name: 'Coffee Pods', default_display_name: 'Coffee pods', subcategory: 'coffee', parent_concept_id: 'food.coffee_tea.coffee.coffee', default_unit: 'box', allowed_units: ['box', 'pack'], search_priority: 74, tags: ['drink', 'coffee'], aliases: [{ alias: 'k-cups', type: 'colloquial' }, { alias: 'keurig pods', type: 'colloquial' }] }),
  item({ ...CT, canonical_id: 'food.coffee_tea.coffee.instant_coffee', canonical_name: 'Instant Coffee', default_display_name: 'Instant coffee', subcategory: 'coffee', parent_concept_id: 'food.coffee_tea.coffee.coffee', default_unit: 'jar', allowed_units: ['jar', 'can'], tags: ['drink', 'coffee'] }),
  item({ ...CT, canonical_id: 'food.coffee_tea.tea.tea', canonical_name: 'Tea', default_display_name: 'Tea', subcategory: 'tea', default_unit: 'box', allowed_units: ['box', 'pack'], search_priority: 76, tags: ['drink', 'staple'], attributes: [{ attribute_id: 'tea.type' }] }),
  item({ ...CT, canonical_id: 'food.coffee_tea.tea.green_tea', canonical_name: 'Green Tea', default_display_name: 'Green tea', subcategory: 'tea', parent_concept_id: 'food.coffee_tea.tea.tea', default_unit: 'box', allowed_units: ['box'], tags: ['drink'], attributes: [{ attribute_id: 'tea.type' }] }),
  item({ ...CT, canonical_id: 'food.coffee_tea.tea.herbal_tea', canonical_name: 'Herbal Tea', default_display_name: 'Herbal tea', subcategory: 'tea', parent_concept_id: 'food.coffee_tea.tea.tea', default_unit: 'box', allowed_units: ['box'], tags: ['drink'], attributes: [{ attribute_id: 'tea.type' }] }),
  item({ ...CT, canonical_id: 'food.coffee_tea.coffee.coffee_creamer', canonical_name: 'Coffee Creamer', default_display_name: 'Coffee creamer', subcategory: 'coffee', default_unit: 'bottle', allowed_units: ['bottle', 'carton'], tags: ['coffee'] }),
  item({ ...CT, canonical_id: 'food.coffee_tea.coffee.hot_chocolate', canonical_name: 'Hot Chocolate', default_display_name: 'Hot chocolate', subcategory: 'coffee', default_unit: 'box', allowed_units: ['box', 'package'], tags: ['drink', 'kids', 'winter'], aliases: [{ alias: 'hot cocoa', type: 'synonym' }] }),
]
