import type { CanonicalItem } from '../types.ts'
import { item } from './_helper.ts'

const BR = { department: 'food', category: 'breakfast', shopping_category: 'breakfast', storage_type: 'ambient' } as const
const SN = { department: 'food', category: 'snacks', shopping_category: 'snacks', storage_type: 'ambient' } as const
const CA = { department: 'food', category: 'candy', shopping_category: 'snacks', storage_type: 'ambient' } as const

export const BREAKFAST_SNACKS: CanonicalItem[] = [
  /* ------------------------------- BREAKFAST ------------------------------- */
  item({ ...BR, canonical_id: 'food.breakfast.cereal.cereal', canonical_name: 'Cereal', default_display_name: 'Cereal', subcategory: 'cereal', default_unit: 'box', allowed_units: ['box', 'bag'], search_priority: 84, tags: ['breakfast', 'kids', 'staple'] }),
  item({ ...BR, canonical_id: 'food.breakfast.oatmeal.oatmeal', canonical_name: 'Oatmeal', default_display_name: 'Oatmeal', subcategory: 'oatmeal', default_unit: 'box', allowed_units: ['box', 'bag'], search_priority: 76, tags: ['breakfast', 'staple'], aliases: [{ alias: 'oats', type: 'colloquial' }, { alias: 'rolled oats', type: 'synonym' }, { alias: 'porridge', type: 'regional' }] }),
  item({ ...BR, canonical_id: 'food.breakfast.oatmeal.instant_oatmeal', canonical_name: 'Instant Oatmeal', default_display_name: 'Instant oatmeal', subcategory: 'oatmeal', parent_concept_id: 'food.breakfast.oatmeal.oatmeal', default_unit: 'box', allowed_units: ['box', 'pack'], tags: ['breakfast', 'kids'] }),
  item({ ...BR, canonical_id: 'food.breakfast.syrup_breakfast.maple_syrup', canonical_name: 'Maple Syrup', default_display_name: 'Maple syrup', subcategory: 'syrup_breakfast', default_unit: 'bottle', allowed_units: ['bottle', 'jar'], search_priority: 72, tags: ['breakfast'] }),
  item({ ...BR, canonical_id: 'food.breakfast.syrup_breakfast.pancake_syrup', canonical_name: 'Pancake Syrup', default_display_name: 'Pancake syrup', subcategory: 'syrup_breakfast', default_unit: 'bottle', allowed_units: ['bottle'], tags: ['breakfast', 'kids'] }),
  item({ ...BR, canonical_id: 'food.breakfast.breakfast_bars.pancake_mix', canonical_name: 'Pancake Mix', default_display_name: 'Pancake mix', subcategory: 'breakfast_bars', default_unit: 'box', allowed_units: ['box', 'bag'], tags: ['breakfast', 'baking'] }),
  item({ ...BR, canonical_id: 'food.breakfast.breakfast_bars.breakfast_bars', canonical_name: 'Breakfast Bars', default_display_name: 'Breakfast bars', subcategory: 'breakfast_bars', default_unit: 'box', allowed_units: ['box', 'pack'], tags: ['breakfast', 'snack', 'school_lunch'] }),
  item({ ...BR, canonical_id: 'food.breakfast.cereal.granola', canonical_name: 'Granola', default_display_name: 'Granola', subcategory: 'cereal', default_unit: 'bag', allowed_units: ['bag', 'box'], tags: ['breakfast', 'snack'] }),
  item({ ...BR, canonical_id: 'food.breakfast.cereal.cream_of_wheat', canonical_name: 'Cream of Wheat', default_display_name: 'Cream of wheat', subcategory: 'cereal', default_unit: 'box', allowed_units: ['box'], tags: ['breakfast'] }),

  /* --------------------------------- SNACKS -------------------------------- */
  item({ ...SN, canonical_id: 'food.snacks.chips.potato_chips', canonical_name: 'Potato Chips', default_display_name: 'Potato chips', subcategory: 'chips', default_unit: 'bag', allowed_units: ['bag'], search_priority: 78, tags: ['snack'], aliases: [{ alias: 'chips', type: 'colloquial' }, { alias: 'crisps', type: 'regional' }] }),
  item({ ...SN, canonical_id: 'food.snacks.chips.tortilla_chips', canonical_name: 'Tortilla Chips', default_display_name: 'Tortilla chips', subcategory: 'chips', default_unit: 'bag', allowed_units: ['bag'], tags: ['snack'], aliases: [{ alias: 'nacho chips', type: 'synonym' }] }),
  item({ ...SN, canonical_id: 'food.snacks.chips.pretzels', canonical_name: 'Pretzels', default_display_name: 'Pretzels', subcategory: 'chips', default_unit: 'bag', allowed_units: ['bag'], tags: ['snack'] }),
  item({ ...SN, canonical_id: 'food.snacks.popcorn.popcorn', canonical_name: 'Popcorn', default_display_name: 'Popcorn', subcategory: 'popcorn', default_unit: 'box', allowed_units: ['box', 'bag'], tags: ['snack'], aliases: [{ alias: 'microwave popcorn', type: 'colloquial' }] }),
  item({ ...SN, canonical_id: 'food.snacks.crackers.crackers', canonical_name: 'Crackers', default_display_name: 'Crackers', subcategory: 'crackers', default_unit: 'box', allowed_units: ['box'], search_priority: 74, tags: ['snack', 'school_lunch'] }),
  item({ ...SN, canonical_id: 'food.snacks.crackers.graham_crackers', canonical_name: 'Graham Crackers', default_display_name: 'Graham crackers', subcategory: 'crackers', default_unit: 'box', allowed_units: ['box'], tags: ['snack', 'baking'] }),
  item({ ...SN, canonical_id: 'food.snacks.crackers.goldfish_crackers', canonical_name: 'Cheese Crackers', default_display_name: 'Cheese crackers', subcategory: 'crackers', default_unit: 'box', allowed_units: ['box', 'bag'], tags: ['snack', 'kids', 'school_lunch'] }),
  item({ ...SN, canonical_id: 'food.snacks.cookies.cookies', canonical_name: 'Cookies', default_display_name: 'Cookies', subcategory: 'cookies', default_unit: 'package', allowed_units: ['package', 'box', 'bag'], search_priority: 74, tags: ['snack', 'dessert'] }),
  item({ ...SN, canonical_id: 'food.snacks.nuts_seeds.almonds', canonical_name: 'Almonds', default_display_name: 'Almonds', subcategory: 'nuts_seeds', default_unit: 'bag', allowed_units: ['bag', 'can'], tags: ['snack', 'nuts'] }),
  item({ ...SN, canonical_id: 'food.snacks.nuts_seeds.peanuts', canonical_name: 'Peanuts', default_display_name: 'Peanuts', subcategory: 'nuts_seeds', default_unit: 'bag', allowed_units: ['bag', 'can'], tags: ['snack', 'nuts'] }),
  item({ ...SN, canonical_id: 'food.snacks.nuts_seeds.cashews', canonical_name: 'Cashews', default_display_name: 'Cashews', subcategory: 'nuts_seeds', default_unit: 'bag', allowed_units: ['bag', 'can'], tags: ['snack', 'nuts'] }),
  item({ ...SN, canonical_id: 'food.snacks.nuts_seeds.mixed_nuts', canonical_name: 'Mixed Nuts', default_display_name: 'Mixed nuts', subcategory: 'nuts_seeds', default_unit: 'can', allowed_units: ['can', 'bag'], tags: ['snack', 'nuts'] }),
  item({ ...SN, canonical_id: 'food.snacks.nuts_seeds.trail_mix', canonical_name: 'Trail Mix', default_display_name: 'Trail mix', subcategory: 'nuts_seeds', default_unit: 'bag', allowed_units: ['bag'], tags: ['snack'] }),
  item({ ...SN, canonical_id: 'food.snacks.dried_fruit_snacks.fruit_snacks', canonical_name: 'Fruit Snacks', default_display_name: 'Fruit snacks', subcategory: 'dried_fruit_snacks', default_unit: 'box', allowed_units: ['box'], tags: ['snack', 'kids', 'school_lunch'], aliases: [{ alias: 'gummies', type: 'colloquial' }] }),
  item({ ...SN, canonical_id: 'food.snacks.dried_fruit_snacks.raisins', canonical_name: 'Raisins', default_display_name: 'Raisins', subcategory: 'dried_fruit_snacks', default_unit: 'box', allowed_units: ['box', 'bag'], tags: ['snack', 'baking', 'school_lunch'] }),
  item({ ...SN, canonical_id: 'food.snacks.bars.granola_bars', canonical_name: 'Granola Bars', default_display_name: 'Granola bars', subcategory: 'bars', default_unit: 'box', allowed_units: ['box', 'pack'], search_priority: 76, tags: ['snack', 'school_lunch'], aliases: [{ alias: 'school bars', type: 'colloquial' }] }),
  item({ ...SN, canonical_id: 'food.snacks.bars.protein_bars', canonical_name: 'Protein Bars', default_display_name: 'Protein bars', subcategory: 'bars', default_unit: 'box', allowed_units: ['box', 'pack'], tags: ['snack', 'protein'] }),
  item({ ...SN, canonical_id: 'food.snacks.chips.veggie_straws', canonical_name: 'Veggie Straws', default_display_name: 'Veggie straws', subcategory: 'chips', default_unit: 'bag', allowed_units: ['bag'], tags: ['snack', 'kids'] }),
  item({ ...SN, canonical_id: 'food.snacks.cookies.rice_cakes', canonical_name: 'Rice Cakes', default_display_name: 'Rice cakes', subcategory: 'cookies', default_unit: 'package', allowed_units: ['package', 'bag'], tags: ['snack'] }),
  item({ ...SN, canonical_id: 'food.snacks.nuts_seeds.sunflower_seeds', canonical_name: 'Sunflower Seeds', default_display_name: 'Sunflower seeds', subcategory: 'nuts_seeds', default_unit: 'bag', allowed_units: ['bag'], tags: ['snack'] }),
  item({ ...SN, canonical_id: 'food.snacks.dried_fruit_snacks.beef_jerky', canonical_name: 'Beef Jerky', default_display_name: 'Beef jerky', subcategory: 'dried_fruit_snacks', default_unit: 'bag', allowed_units: ['bag', 'package'], tags: ['snack', 'protein'] }),

  /* ---------------------------------- CANDY -------------------------------- */
  item({ ...CA, canonical_id: 'food.candy.chocolate.chocolate_bar', canonical_name: 'Chocolate Bar', default_display_name: 'Chocolate bars', subcategory: 'chocolate', default_unit: 'each', allowed_units: ['each', 'pack', 'box'], search_priority: 70, tags: ['candy', 'snack'], aliases: [{ alias: 'candy bar', type: 'synonym' }] }),
  item({ ...CA, canonical_id: 'food.candy.chocolate.chocolate_chips', canonical_name: 'Chocolate Chips', default_display_name: 'Chocolate chips', subcategory: 'chocolate', default_unit: 'bag', allowed_units: ['bag'], tags: ['baking'] }),
  item({ ...CA, canonical_id: 'food.candy.gummy.gummy_candy', canonical_name: 'Gummy Candy', default_display_name: 'Gummy candy', subcategory: 'gummy', default_unit: 'bag', allowed_units: ['bag'], tags: ['candy'], aliases: [{ alias: 'gummies', type: 'colloquial' }, { alias: 'gummy bears', type: 'colloquial' }] }),
  item({ ...CA, canonical_id: 'food.candy.hard_candy.lollipops', canonical_name: 'Lollipops', default_display_name: 'Lollipops', subcategory: 'hard_candy', default_unit: 'bag', allowed_units: ['bag'], tags: ['candy', 'kids'] }),
  item({ ...CA, canonical_id: 'food.candy.gummy.mints', canonical_name: 'Mints', default_display_name: 'Mints', subcategory: 'hard_candy', default_unit: 'package', allowed_units: ['package', 'each'], tags: ['candy'] }),
  item({ ...CA, canonical_id: 'food.candy.gummy.gum', canonical_name: 'Gum', default_display_name: 'Gum', subcategory: 'hard_candy', default_unit: 'package', allowed_units: ['package', 'each'], tags: ['candy'], aliases: [{ alias: 'chewing gum', type: 'synonym' }] }),
]
