import type { CanonicalItem } from '../types.ts'
import { item } from './_helper.ts'

const CO = { department: 'food', category: 'condiments_sauces', shopping_category: 'pantry', storage_type: 'ambient' } as const
const BK = { department: 'food', category: 'baking', shopping_category: 'pantry', storage_type: 'ambient' } as const
const SP = { department: 'food', category: 'herbs_spices_seasonings', shopping_category: 'pantry', storage_type: 'ambient' } as const
const OI = { department: 'food', category: 'oils_cooking_fats', shopping_category: 'pantry', storage_type: 'ambient' } as const
const NB = { department: 'food', category: 'nut_butters_jams_spreads', shopping_category: 'pantry', storage_type: 'ambient' } as const

export const CONDIMENTS_BAKING_SPICES: CanonicalItem[] = [
  /* ------------------------------ CONDIMENTS ------------------------------- */
  item({ ...CO, canonical_id: 'food.condiments_sauces.condiment.ketchup', canonical_name: 'Ketchup', default_display_name: 'Ketchup', subcategory: 'condiment', default_unit: 'bottle', allowed_units: ['bottle', 'mL'], search_priority: 78, tags: ['condiment', 'staple'] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.condiment.mustard', canonical_name: 'Mustard', default_display_name: 'Mustard', subcategory: 'condiment', default_unit: 'bottle', allowed_units: ['bottle', 'jar'], tags: ['condiment'] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.condiment.mayonnaise', canonical_name: 'Mayonnaise', default_display_name: 'Mayonnaise', subcategory: 'condiment', default_unit: 'jar', allowed_units: ['jar', 'bottle'], search_priority: 74, tags: ['condiment', 'staple'], aliases: [{ alias: 'mayo', type: 'abbreviation' }] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.condiment.relish', canonical_name: 'Relish', default_display_name: 'Relish', subcategory: 'condiment', default_unit: 'jar', allowed_units: ['jar'], tags: ['condiment'] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.condiment.bbq_sauce', canonical_name: 'BBQ Sauce', default_display_name: 'BBQ sauce', subcategory: 'condiment', default_unit: 'bottle', allowed_units: ['bottle'], tags: ['condiment', 'summer'], aliases: [{ alias: 'barbecue sauce', type: 'synonym' }] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.condiment.hot_sauce', canonical_name: 'Hot Sauce', default_display_name: 'Hot sauce', subcategory: 'condiment', default_unit: 'bottle', allowed_units: ['bottle'], tags: ['condiment', 'spicy'] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.asian_sauce.soy_sauce', canonical_name: 'Soy Sauce', default_display_name: 'Soy sauce', subcategory: 'asian_sauce', default_unit: 'bottle', allowed_units: ['bottle'], search_priority: 72, tags: ['condiment', 'cooking'] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.condiment.worcestershire', canonical_name: 'Worcestershire Sauce', default_display_name: 'Worcestershire sauce', subcategory: 'condiment', default_unit: 'bottle', allowed_units: ['bottle'], tags: ['cooking'] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.dressing.salad_dressing', canonical_name: 'Salad Dressing', default_display_name: 'Salad dressing', subcategory: 'dressing', default_unit: 'bottle', allowed_units: ['bottle'], search_priority: 72, tags: ['condiment', 'salad'], aliases: [{ alias: 'dressing', type: 'colloquial' }] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.dressing.ranch_dressing', canonical_name: 'Ranch Dressing', default_display_name: 'Ranch dressing', subcategory: 'dressing', parent_concept_id: 'food.condiments_sauces.dressing.salad_dressing', default_unit: 'bottle', allowed_units: ['bottle'], tags: ['condiment', 'salad', 'kids'], aliases: [{ alias: 'ranch', type: 'colloquial' }] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.salsa_dip.salsa', canonical_name: 'Salsa', default_display_name: 'Salsa', subcategory: 'salsa_dip', default_unit: 'jar', allowed_units: ['jar', 'tub'], search_priority: 72, tags: ['snack', 'dip', 'mexican'] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.salsa_dip.guacamole', canonical_name: 'Guacamole', default_display_name: 'Guacamole', subcategory: 'salsa_dip', default_unit: 'tub', allowed_units: ['tub', 'package'], tags: ['snack', 'dip'] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.condiment.pickles', canonical_name: 'Pickles', default_display_name: 'Pickles', subcategory: 'condiment', default_unit: 'jar', allowed_units: ['jar'], tags: ['condiment', 'snack'] }),
  item({ ...CO, canonical_id: 'food.condiments_sauces.condiment.honey_mustard', canonical_name: 'Honey Mustard', default_display_name: 'Honey mustard', subcategory: 'condiment', default_unit: 'bottle', allowed_units: ['bottle'], tags: ['condiment'] }),

  /* -------------------------------- BAKING --------------------------------- */
  item({ ...BK, canonical_id: 'food.baking.flour.all_purpose_flour', canonical_name: 'All-Purpose Flour', default_display_name: 'Flour', subcategory: 'flour', default_unit: 'bag', allowed_units: ['bag', 'kg', 'lb'], search_priority: 78, tags: ['baking', 'staple'], aliases: [{ alias: 'flour', type: 'colloquial' }, { alias: 'ap flour', type: 'abbreviation' }] }),
  item({ ...BK, canonical_id: 'food.baking.sugar.white_sugar', canonical_name: 'White Sugar', default_display_name: 'Sugar', subcategory: 'sugar', default_unit: 'bag', allowed_units: ['bag', 'kg'], search_priority: 78, tags: ['baking', 'staple'], aliases: [{ alias: 'sugar', type: 'colloquial' }, { alias: 'granulated sugar', type: 'synonym' }] }),
  item({ ...BK, canonical_id: 'food.baking.sugar.brown_sugar', canonical_name: 'Brown Sugar', default_display_name: 'Brown sugar', subcategory: 'sugar', default_unit: 'bag', allowed_units: ['bag', 'kg'], tags: ['baking'] }),
  item({ ...BK, canonical_id: 'food.baking.sugar.powdered_sugar', canonical_name: 'Powdered Sugar', default_display_name: 'Powdered sugar', subcategory: 'sugar', default_unit: 'bag', allowed_units: ['bag', 'kg'], tags: ['baking'], aliases: [{ alias: 'icing sugar', type: 'regional', locale: 'en-CA' }, { alias: 'confectioners sugar', type: 'regional', locale: 'en-US' }, { alias: "confectioner's sugar", type: 'regional', locale: 'en-US' }] }),
  item({ ...BK, canonical_id: 'food.baking.leavening.baking_soda', canonical_name: 'Baking Soda', default_display_name: 'Baking soda', subcategory: 'leavening', default_unit: 'box', allowed_units: ['box'], tags: ['baking', 'staple'] }),
  item({ ...BK, canonical_id: 'food.baking.leavening.baking_powder', canonical_name: 'Baking Powder', default_display_name: 'Baking powder', subcategory: 'leavening', default_unit: 'can', allowed_units: ['can', 'box'], tags: ['baking'] }),
  item({ ...BK, canonical_id: 'food.baking.leavening.yeast', canonical_name: 'Yeast', default_display_name: 'Yeast', subcategory: 'leavening', default_unit: 'package', allowed_units: ['package', 'jar'], tags: ['baking'] }),
  item({ ...BK, canonical_id: 'food.baking.extracts.vanilla_extract', canonical_name: 'Vanilla Extract', default_display_name: 'Vanilla extract', subcategory: 'extracts', default_unit: 'bottle', allowed_units: ['bottle'], tags: ['baking'], aliases: [{ alias: 'vanilla', type: 'colloquial' }] }),
  item({ ...BK, canonical_id: 'food.baking.baking_mix.cake_mix', canonical_name: 'Cake Mix', default_display_name: 'Cake mix', subcategory: 'baking_mix', default_unit: 'box', allowed_units: ['box'], tags: ['baking', 'dessert'] }),
  item({ ...BK, canonical_id: 'food.baking.baking_mix.brownie_mix', canonical_name: 'Brownie Mix', default_display_name: 'Brownie mix', subcategory: 'baking_mix', default_unit: 'box', allowed_units: ['box'], tags: ['baking', 'dessert'] }),
  item({ ...BK, canonical_id: 'food.baking.baking_add_ins.cornstarch', canonical_name: 'Cornstarch', default_display_name: 'Cornstarch', subcategory: 'baking_add_ins', default_unit: 'box', allowed_units: ['box'], tags: ['baking', 'cooking'], aliases: [{ alias: 'corn starch', type: 'synonym' }] }),
  item({ ...BK, canonical_id: 'food.baking.baking_add_ins.cocoa_powder', canonical_name: 'Cocoa Powder', default_display_name: 'Cocoa powder', subcategory: 'baking_add_ins', default_unit: 'can', allowed_units: ['can', 'box'], tags: ['baking'] }),
  item({ ...BK, canonical_id: 'food.baking.sugar.molasses', canonical_name: 'Molasses', default_display_name: 'Molasses', subcategory: 'sugar', default_unit: 'bottle', allowed_units: ['bottle', 'jar'], tags: ['baking'] }),

  /* -------------------------------- SPICES --------------------------------- */
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.salt.salt', canonical_name: 'Salt', default_display_name: 'Salt', subcategory: 'salt', default_unit: 'box', allowed_units: ['box', 'g', 'kg'], search_priority: 74, tags: ['seasoning', 'staple'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.pepper.black_pepper', canonical_name: 'Black Pepper', default_display_name: 'Black pepper', subcategory: 'pepper', default_unit: 'jar', allowed_units: ['jar', 'g'], search_priority: 74, tags: ['seasoning', 'staple'], aliases: [{ alias: 'pepper', type: 'colloquial' }] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.cinnamon', canonical_name: 'Cinnamon', default_display_name: 'Cinnamon', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g'], tags: ['spice', 'baking'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.paprika', canonical_name: 'Paprika', default_display_name: 'Paprika', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g'], tags: ['spice'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.cumin', canonical_name: 'Cumin', default_display_name: 'Cumin', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g'], tags: ['spice'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.chili_powder', canonical_name: 'Chili Powder', default_display_name: 'Chili powder', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g'], tags: ['spice'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.garlic_powder', canonical_name: 'Garlic Powder', default_display_name: 'Garlic powder', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g'], tags: ['spice', 'seasoning'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.onion_powder', canonical_name: 'Onion Powder', default_display_name: 'Onion powder', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g'], tags: ['spice', 'seasoning'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.oregano', canonical_name: 'Oregano', default_display_name: 'Oregano', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g'], tags: ['spice', 'dried_herb'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.basil_dried', canonical_name: 'Dried Basil', default_display_name: 'Dried basil', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g'], tags: ['spice', 'dried_herb'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.ginger_ground', canonical_name: 'Ground Ginger', default_display_name: 'Ground ginger', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g'], tags: ['spice', 'baking'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.nutmeg', canonical_name: 'Nutmeg', default_display_name: 'Nutmeg', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g'], tags: ['spice', 'baking'] }),
  // §13 CORIANDER RULE — the SEED is its own spice; must NOT merge with cilantro (produce).
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.coriander_seed', canonical_name: 'Coriander Seed', default_display_name: 'Coriander seed', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar', 'g', 'package'], tags: ['spice'], aliases: [{ alias: 'ground coriander', type: 'synonym' }] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.seasoning.italian_seasoning', canonical_name: 'Italian Seasoning', default_display_name: 'Italian seasoning', subcategory: 'seasoning', default_unit: 'jar', allowed_units: ['jar'], tags: ['seasoning'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.seasoning.taco_seasoning', canonical_name: 'Taco Seasoning', default_display_name: 'Taco seasoning', subcategory: 'seasoning', default_unit: 'package', allowed_units: ['package', 'jar'], search_priority: 70, tags: ['seasoning', 'mexican'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.bay_leaves', canonical_name: 'Bay Leaves', default_display_name: 'Bay leaves', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar'], tags: ['spice', 'dried_herb'] }),
  item({ ...SP, canonical_id: 'food.herbs_spices_seasonings.spice.red_pepper_flakes', canonical_name: 'Red Pepper Flakes', default_display_name: 'Red pepper flakes', subcategory: 'spice', default_unit: 'jar', allowed_units: ['jar'], tags: ['spice', 'spicy'], aliases: [{ alias: 'chili flakes', type: 'synonym' }] }),

  /* --------------------------------- OILS ---------------------------------- */
  item({ ...OI, canonical_id: 'food.oils_cooking_fats.oil.olive_oil', canonical_name: 'Olive Oil', default_display_name: 'Olive oil', subcategory: 'oil', default_unit: 'bottle', allowed_units: ['bottle', 'mL', 'L'], search_priority: 76, tags: ['cooking', 'staple'] }),
  item({ ...OI, canonical_id: 'food.oils_cooking_fats.oil.vegetable_oil', canonical_name: 'Vegetable Oil', default_display_name: 'Vegetable oil', subcategory: 'oil', default_unit: 'bottle', allowed_units: ['bottle', 'L'], search_priority: 72, tags: ['cooking', 'staple'], aliases: [{ alias: 'canola oil', type: 'synonym' }] }),
  item({ ...OI, canonical_id: 'food.oils_cooking_fats.oil.cooking_spray', canonical_name: 'Cooking Spray', default_display_name: 'Cooking spray', subcategory: 'oil', default_unit: 'can', allowed_units: ['can'], tags: ['cooking'], aliases: [{ alias: 'pam', type: 'colloquial' }] }),
  item({ ...OI, canonical_id: 'food.oils_cooking_fats.vinegar.vinegar', canonical_name: 'Vinegar', default_display_name: 'Vinegar', subcategory: 'vinegar', default_unit: 'bottle', allowed_units: ['bottle', 'L'], tags: ['cooking', 'pantry'] }),
  item({ ...OI, canonical_id: 'food.oils_cooking_fats.vinegar.balsamic_vinegar', canonical_name: 'Balsamic Vinegar', default_display_name: 'Balsamic vinegar', subcategory: 'vinegar', default_unit: 'bottle', allowed_units: ['bottle'], tags: ['cooking', 'salad'] }),

  /* ---------------------- NUT BUTTERS / JAMS / SPREADS --------------------- */
  item({ ...NB, canonical_id: 'food.nut_butters_jams_spreads.nut_butter.peanut_butter', canonical_name: 'Peanut Butter', default_display_name: 'Peanut butter', subcategory: 'nut_butter', default_unit: 'jar', allowed_units: ['jar', 'g'], search_priority: 80, tags: ['sandwich', 'snack', 'staple'], aliases: [{ alias: 'pb', type: 'abbreviation' }] }),
  item({ ...NB, canonical_id: 'food.nut_butters_jams_spreads.nut_butter.almond_butter', canonical_name: 'Almond Butter', default_display_name: 'Almond butter', subcategory: 'nut_butter', default_unit: 'jar', allowed_units: ['jar'], tags: ['sandwich', 'snack'] }),
  item({ ...NB, canonical_id: 'food.nut_butters_jams_spreads.jam.jam', canonical_name: 'Jam', default_display_name: 'Jam', subcategory: 'jam', default_unit: 'jar', allowed_units: ['jar'], search_priority: 74, tags: ['sandwich', 'breakfast'], aliases: [{ alias: 'jelly', type: 'synonym' }, { alias: 'preserves', type: 'synonym' }] }),
  item({ ...NB, canonical_id: 'food.nut_butters_jams_spreads.honey_syrup.honey', canonical_name: 'Honey', default_display_name: 'Honey', subcategory: 'honey_syrup', default_unit: 'jar', allowed_units: ['jar', 'bottle'], tags: ['breakfast', 'baking'] }),
]
