import type { CanonicalItem } from '../types.ts'
import { item } from './_helper.ts'

const F = { department: 'food', category: 'frozen', shopping_category: 'frozen', storage_type: 'frozen' } as const

export const FROZEN: CanonicalItem[] = [
  item({ ...F, canonical_id: 'food.frozen.frozen_vegetables.frozen_peas', canonical_name: 'Frozen Peas', default_display_name: 'Frozen peas', subcategory: 'frozen_vegetables', default_unit: 'bag', allowed_units: ['bag', 'g'], search_priority: 70, tags: ['vegetable', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_vegetables.frozen_corn', canonical_name: 'Frozen Corn', default_display_name: 'Frozen corn', subcategory: 'frozen_vegetables', default_unit: 'bag', allowed_units: ['bag'], tags: ['vegetable', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_vegetables.frozen_broccoli', canonical_name: 'Frozen Broccoli', default_display_name: 'Frozen broccoli', subcategory: 'frozen_vegetables', default_unit: 'bag', allowed_units: ['bag'], tags: ['vegetable', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_vegetables.frozen_mixed_vegetables', canonical_name: 'Frozen Mixed Vegetables', default_display_name: 'Frozen mixed vegetables', subcategory: 'frozen_vegetables', default_unit: 'bag', allowed_units: ['bag'], tags: ['vegetable', 'freezer'], aliases: [{ alias: 'frozen veggies', type: 'colloquial' }] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_vegetables.frozen_spinach', canonical_name: 'Frozen Spinach', default_display_name: 'Frozen spinach', subcategory: 'frozen_vegetables', default_unit: 'box', allowed_units: ['box', 'bag'], tags: ['vegetable', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_fruit.frozen_berries', canonical_name: 'Frozen Berries', default_display_name: 'Frozen berries', subcategory: 'frozen_fruit', default_unit: 'bag', allowed_units: ['bag'], search_priority: 68, tags: ['fruit', 'smoothie', 'freezer'], aliases: [{ alias: 'frozen blueberries', type: 'colloquial' }, { alias: 'frozen strawberries', type: 'colloquial' }, { alias: 'frozen mixed berries', type: 'synonym' }] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_fruit.frozen_mango', canonical_name: 'Frozen Mango', default_display_name: 'Frozen mango', subcategory: 'frozen_fruit', default_unit: 'bag', allowed_units: ['bag'], tags: ['fruit', 'smoothie', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_potato.french_fries', canonical_name: 'French Fries', default_display_name: 'French fries', subcategory: 'frozen_potato', default_unit: 'bag', allowed_units: ['bag'], search_priority: 70, tags: ['dinner', 'freezer', 'kids'], aliases: [{ alias: 'fries', type: 'colloquial' }, { alias: 'frozen fries', type: 'synonym' }] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_potato.hash_browns', canonical_name: 'Hash Browns', default_display_name: 'Hash browns', subcategory: 'frozen_potato', default_unit: 'bag', allowed_units: ['bag', 'box'], tags: ['breakfast', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_potato.tater_tots', canonical_name: 'Tater Tots', default_display_name: 'Tater tots', subcategory: 'frozen_potato', default_unit: 'bag', allowed_units: ['bag'], tags: ['dinner', 'kids', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_pizza.frozen_pizza', canonical_name: 'Frozen Pizza', default_display_name: 'Frozen pizza', subcategory: 'frozen_pizza', default_unit: 'each', allowed_units: ['each', 'box'], search_priority: 72, tags: ['dinner', 'freezer', 'kids'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_meals.frozen_dinner', canonical_name: 'Frozen Dinner', default_display_name: 'Frozen dinner', subcategory: 'frozen_meals', default_unit: 'each', allowed_units: ['each', 'box'], tags: ['dinner', 'freezer'], aliases: [{ alias: 'frozen meal', type: 'synonym' }, { alias: 'tv dinner', type: 'colloquial' }] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_meals.frozen_lasagna', canonical_name: 'Frozen Lasagna', default_display_name: 'Frozen lasagna', subcategory: 'frozen_meals', default_unit: 'each', allowed_units: ['each', 'box'], tags: ['dinner', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_protein.chicken_nuggets', canonical_name: 'Chicken Nuggets', default_display_name: 'Chicken nuggets', subcategory: 'frozen_protein', default_unit: 'bag', allowed_units: ['bag', 'box'], search_priority: 72, tags: ['dinner', 'kids', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_protein.chicken_strips', canonical_name: 'Chicken Strips', default_display_name: 'Chicken strips', subcategory: 'frozen_protein', default_unit: 'bag', allowed_units: ['bag', 'box'], tags: ['dinner', 'kids', 'freezer'], aliases: [{ alias: 'chicken fingers', type: 'synonym' }] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_protein.fish_sticks', canonical_name: 'Fish Sticks', default_display_name: 'Fish sticks', subcategory: 'frozen_protein', default_unit: 'box', allowed_units: ['box', 'bag'], tags: ['dinner', 'kids', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_protein.frozen_burgers', canonical_name: 'Frozen Burgers', default_display_name: 'Frozen burgers', subcategory: 'frozen_protein', default_unit: 'box', allowed_units: ['box', 'bag'], tags: ['dinner', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_breakfast.frozen_waffles', canonical_name: 'Frozen Waffles', default_display_name: 'Frozen waffles', subcategory: 'frozen_breakfast', default_unit: 'box', allowed_units: ['box'], tags: ['breakfast', 'kids', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_dessert.ice_cream', canonical_name: 'Ice Cream', default_display_name: 'Ice cream', subcategory: 'frozen_dessert', default_unit: 'tub', allowed_units: ['tub', 'L', 'each'], search_priority: 78, tags: ['dessert', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_dessert.popsicles', canonical_name: 'Popsicles', default_display_name: 'Popsicles', subcategory: 'frozen_dessert', default_unit: 'box', allowed_units: ['box'], tags: ['dessert', 'kids', 'summer'], aliases: [{ alias: 'freezies', type: 'regional', locale: 'en-CA' }, { alias: 'ice pops', type: 'synonym' }] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_dessert.frozen_yogurt', canonical_name: 'Frozen Yogurt', default_display_name: 'Frozen yogurt', subcategory: 'frozen_dessert', default_unit: 'tub', allowed_units: ['tub'], tags: ['dessert', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_breakfast.frozen_pancakes', canonical_name: 'Frozen Pancakes', default_display_name: 'Frozen pancakes', subcategory: 'frozen_breakfast', default_unit: 'box', allowed_units: ['box'], tags: ['breakfast', 'kids', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_meals.perogies', canonical_name: 'Perogies', default_display_name: 'Perogies', subcategory: 'frozen_meals', default_unit: 'bag', allowed_units: ['bag', 'box'], tags: ['dinner', 'freezer'], aliases: [{ alias: 'pierogies', type: 'synonym' }, { alias: 'pierogi', type: 'synonym' }] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_protein.frozen_shrimp', canonical_name: 'Frozen Shrimp', default_display_name: 'Frozen shrimp', subcategory: 'frozen_protein', default_unit: 'bag', allowed_units: ['bag'], tags: ['protein', 'seafood', 'freezer'] }),
  item({ ...F, canonical_id: 'food.frozen.frozen_breakfast.frozen_breakfast_sandwich', canonical_name: 'Frozen Breakfast Sandwich', default_display_name: 'Frozen breakfast sandwiches', subcategory: 'frozen_breakfast', default_unit: 'box', allowed_units: ['box'], tags: ['breakfast', 'freezer'] }),
]
